### ISSUE TITLE
Map is cut on top and bottom

### ISSUE THREAD

**Issue by philipinf** [sgratzl/chartjs-chart-geo#100]
Hi,

I created a choropleth of germany and on the top and bottom the map is cut off. The red border in the picture is the wrapping div and the green border is the canvas. As you can see there is no overflow.

![image](https://user-images.githubusercontent.com/40243017/153594063-9c65a5de-6a4a-43dd-a76a-ba8dad234666.png)

I used the same [data](https://github.com/deldersveld/topojson/tree/master/countries/germany) as in the germany example from this repository. Adding padding in the options of the chart didnt change anything.

This is my full chart configuration
``` 
import { topojson } from 'chartjs-chart-geo';
import { Chart, ChartData, ChartOptions, registerables } from 'chart.js';
Chart.register(...registerables);

this.states = topojson
	.feature(germanyStates, germanyStates.objects.layer)
	.features.filter((item) => item.properties.NAME_0 === 'Germany');
const countries = topojson.feature(germany, germany.objects.continent_Europe_subunits).features;
this.germany = countries.find((d) => d.properties.geounit === 'Germany');

this.chart = new Chart(this.chartCtx, {
      type: 'choropleth',
      data: {
	      labels: this.currentData.map((d) => d.feature.properties.NAME_1),
	      datasets: [
		      {
			      label: this.currentDate,
			      outline: this.germany,
			      borderColor: '#000000',
			      borderWidth: 2,
			      data: this.currentData
		      },
	      ],
      },
      options: {
	      layout: {
		      padding: {
			      top: 5,
			      bottom: 5,
		      },
	      },
	      maintainAspectRatio: true,
	      responsive: true,
	      showOutline: false,
	      showGraticule: false,
	      plugins: {
		      legend: {
			      display: true,
		      },
	      },
	      scales: {
		      xy: {
			      projection: 'equalEarth',
		      },
	      },
      },
});
```

- Version: chartjs-chart-geo@3.6.0
- Browser: Chrome 98.0.4758.82

Thanks for your help in advance

**Comment by sgratzl** [comment]
take a look at the new padding option in the latest release 3.7.0 ->https://github.com/sgratzl/chartjs-chart-geo/blob/effcfe7dad5be67ddc6461c582bfba3420ce70ee/samples/germany.html#L53

**Comment by philipinf** [comment]
Thanks for the fast response. That did indeed fix the problem :)
