### ISSUE TITLE
Outline width and backgroundColor on bubbleMap

### ISSUE THREAD

**Issue by philipinf** [sgratzl/chartjs-chart-geo#103]
Hi,

how can I set the width of the outline and the backgroundColor in the bubbleMap chart? In the choropleth chart you can set it inside the dataset like this

```
{
  label: this.currentDate,
  outline: this.germany,
  borderColor: '#000000',
  borderWidth: 2,
  data: this.currentData
}
```
which will produce the following map.

![image](https://user-images.githubusercontent.com/40243017/153708294-5d54478a-9570-4424-b235-18231b9d5c2a.png)

But i cant get the same effect for the bubbleMap, because the borderWidth and backgroundColor is targeting the dots and not the states.

```
{
  label: this.currentDate,
  outline: this.states,
  borderColor: '#000000',
  borderWidth: 2,
  backgroundColor: '#05396b',
  data: this.currentData,
}
```

![image](https://user-images.githubusercontent.com/40243017/153708230-dc16b76d-1d8c-49b9-bf5b-27d802d55745.png)

- Version: chartjs-chart-geo@3.7.0
- Browser: Chrome 98.0.4758.82

Thanks for your help in advance

**Comment by sgratzl** [comment]
have you tried setting one of those options:

https://github.com/sgratzl/chartjs-chart-geo/blob/effcfe7dad5be67ddc6461c582bfba3420ce70ee/src/elements/GeoFeature.ts#L6-L20

**Comment by philipinf** [comment]
That worked thanks :)
