### ISSUE TITLE
Any plan to remove commonjs?

### ISSUE THREAD

**Issue by elvince** [sgratzl/chartjs-chart-geo#104]
Hi,

As per Angular recommandation, did you planned to remove the dependency on commonjs ?

Thanks

**Comment by sgratzl** [comment]
which depedency do you mean? this repo generates ESM, CJS, and UMD builds?

**Comment by elvince** [comment]
XXX.component.ts depends on 'chartjs-chart-geo'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I'm not an expert, but here is what I got when building.

**Comment by sgratzl** [comment]
as I said, this package is generating an ESM build and correctly references it using the `module` keyword. see https://github.com/sgratzl/chartjs-chart-geo/blob/effcfe7dad5be67ddc6461c582bfba3420ce70ee/package.json#L27-L33

**Comment by sgratzl** [comment]
wontfix
