### ISSUE TITLE
Can't set geoFeature on Elements in Option

### ISSUE THREAD

**Issue by elvince** [sgratzl/chartjs-chart-geo#106]
In typescript, when I'm trying to set the styling, I have this issue:

**Object literal may only specify known properties, and 'geoFeature' does not exist in type '_DeepPartialObject<ElementOptionsByType<"choropleth">>'.
 The expected type comes from property 'elements' which is declared here on type '_DeepPartialObject<CoreChartOptions<"choropleth"> & ElementChartOptions<"choropleth"> & PluginChartOptions<"choropleth"> & DatasetChartOptions<...> & ScaleChartOptions<...> & IGeoChartOptions>'
**

There is no issue in the sample [codePen](https://codepen.io/sgratzl/pen/gOaBQep) if I add 
` elements:{
        geoFeature: {
          borderColor: "#686868",
          //backgroundColor: "#00FF00"
          },
      },`

Any Idea why typescript is complaining?

Thanks for your help

**Comment by sgratzl** [comment]
it is difficult to extent chart.js with extra typings and making sure that it works in every scenario. Happy to review a PR that fixes the issue if you can resolve it.

**Comment by elvince** [comment]
I will try to help by providing something.
As far as I look, I can't find any ElementChartOptions extension that should provide the geofeature as an option.

Does that make sense?

**Comment by etimberg** [comment]
The solution here is to have the `GeoFeature` element update the `ElementOptionsByType` interface similar to how the scale registry is updated. 

[Working example](https://www.typescriptlang.org/play?ts=4.4.4#code/JYWwDg9gTgLgBAbzgYQBYENYBoUdgeTBmAgDsBnOAXzgDMoIQ4ByAYzxgDoArc5gbgCwAKFCRYiXNAhgANgFMYqZGRgNZCqDhWzoAZVboFOAOLyIAMXnoYAVyjycASTOXrdh4WJlyOAAoM3PKs3qQGRo5wMDIQvGTUdAxMAETsmDC8ALRpsJkA5ubJQsIiuOmcDnnA5DDyUAAUaNJyisqq6pqm5lY29pE6+obGcAGxwaHhCgCUxaUAJsGymPJwIBBztgosOVy8zIilcHDyAB7i8MCktVC06KwrrgCiCiDyV14kFABCAJ4AKj8wCsEIcjnACm5eg4AFxwFzddx9D4+UFUESg07nOCXa63e5wZ7yV7vIifci-AFAgA8f0p8gAfMcTrVSHNKE8Xm8YMjvv9AcC0cJqOjhAA3TBwEInOAAXjgcwgrFsxK4BRghJVvycc3qyRAPzQ6WSUzg6EoAAk-gBZAAyyHQpHF5A1XOK4qgqwNHBkMFhZQIpJ8VNSqGaCiUyUZcpBQrB8k5V3IsJjYLBEJ6HnkydBqbgACNoAsoAMoLDkgBiABsAA4azXklgc0cqI3Y83W83+EA)

**Comment by sgratzl** [comment]
added in https://github.com/sgratzl/chartjs-chart-geo/blob/3a68ac39c5d580f86617a85554afb3923a4aee51/src/elements/GeoFeature.ts#L193-L196

**Comment by sgratzl** [comment]
should be fixed with v3.7.1

**Comment by elvince** [comment]
Thanks both of you for your support.
