### ISSUE TITLE
Tooltips don't work with 2.9.x

### ISSUE THREAD

**Issue by aceluby** [sgratzl/chartjs-chart-geo#11]
**Describe the bug**
Tooltips don't work with 2.9.x of chart.js

**To Reproduce**
Use 2.8.0 chart.js, implement a tooltip, then upgrade to 2.9 and they no longer work.

**Expected behavior**
Tooltips should work on all versions of chart.js

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
Seems to be a known issue as it was referenced in the closed issue regarding the compatibility of 2.9.x.  This is how I found that downgrading chart.js to 2.8.0 got tooltips to work again.

**Comment by sgratzl** [comment]
do you mean while showing a map or a bubble map?

**Comment by sgratzl** [comment]
should be fixed with https://github.com/sgratzl/chartjs-chart-geo/releases/tag/v1.1.3
