### ISSUE TITLE
Disable legend on bubbleMap

### ISSUE THREAD

**Issue by philipinf** [sgratzl/chartjs-chart-geo#114]
Hi,

is there a possibility to hide the legend of the bubbleMap? As you can see in the image below the legend is overlapping the chart and I want to disable it if that happens. I couldn't find a property that I could set. For the Choropleth chart you can set scales.color.display = false and it works but not for the bubbleMap

![image](https://user-images.githubusercontent.com/40243017/173193082-34c6857a-903c-4bc5-8da1-4802c4404f05.png)

- Version: chartjs-chart-geo@3.7.0
- Browser: Chrome 102.0.5005.63

Thanks for your help in advance

**Comment by sgratzl** [comment]
have you tried `scales.size.disable= false`?

**Comment by philipinf** [comment]
Did you mean ``scales.size.display= false`` ?
I tried that and your suggestion with true and false but nothing worked

**Comment by sgratzl** [comment]
sorry I was thinking the wrong one, try: `scales.r.display = false`

**Comment by philipinf** [comment]
Yes that worked, thanks :)
