### ISSUE TITLE
Tooltips don't always appear on the correct country.

### ISSUE THREAD

**Issue by thibaultzanini** [sgratzl/chartjs-chart-geo#115]
Hi,

First of all, thanks for you work! 

I noticed an issue with tooltips, sometime they appear over the wrong country.
For instance, when I move my mouse over France, the tooltip appears over Spain.

**To Reproduce**

```
fetch("https://unpkg.com/world-atlas/countries-50m.json")
  .then((r) => r.json())
  .then((data) => {
    const countries = ChartGeo.topojson.feature(
      data,
      data.objects.countries
    ).features;

    const chart = new Chart(
      document.getElementById("canvas").getContext("2d"),
      {
        type: "choropleth",
        data: {
          labels: countries.map((country) => country.properties.name),
          datasets: [
            {
              label: "Countries",
              data: countries.map((country) => ({
                feature: country,
                value: Math.random(),
              })),
            },
          ],
        },
        options: {
          showOutline: false,
          showGraticule: false,
          plugins: {
            legend: {
              display: false,
            },
          },
          scales: {
            xy: {
              projection: "equirectangular",
            },
          },
        },
      }
    );
  });
```

**Expected behavior**

Tooltips should appear on the correct country.

**Screenshots**

![image](https://user-images.githubusercontent.com/3347451/176231189-ab4f23c9-744e-4811-b3fe-3aca0737ddb5.png)

**Context**

- Version: 3.8.0
- Browser: Chrome 103.0.5060.53

**Comment by sgratzl** [comment]
French Guiana is part of France and the centroid of the country is used for the tooltip:

![image](https://user-images.githubusercontent.com/4129778/176329918-36a50583-b398-422e-8974-ebfa92e12907.png)

**Comment by sgratzl** [comment]
see also upcoming in the next release #118

**Comment by thibaultzanini** [comment]
Thanks a lot, I really appreciate it :)
