### ISSUE TITLE
Is it possible to translate the projection?

### ISSUE THREAD

**Issue by thibaultzanini** [sgratzl/chartjs-chart-geo#116]
Hi,

I would like to display Russia undivided, so I was wondering if it possible to translate the projection? I tried to use the `projectionOffset`, but it didn't work. Any idea?

Thanks. :)

**Screenshots / Sketches**

![Screenshot 2022-06-28 at 19 03 08](https://user-images.githubusercontent.com/3347451/176241148-e7c213a6-03cc-4c9a-9acb-9e2f46da1c30.png)

**Context**

- Version: 3.8.0
- Browser: 103.0.5060.53

**Comment by sgratzl** [comment]
can you provide an example to reproduce, please

**Comment by thibaultzanini** [comment]
Yeah sorry:

```fetch("https://unpkg.com/world-atlas/countries-50m.json")
  .then((r) => r.json())
  .then((data) => {
    const countries = ChartGeo.topojson.feature(
      data,
      data.objects.countries
    ).features;

    const chart = new Chart(
      document.getElementById("canvas").getContext("2d"),
      {
        type: "choropleth",
        data: {
          labels: countries.map((country) => country.properties.name),
          datasets: [
            {
              label: "Countries",
              data: countries.map((country) => ({
                feature: country,
                value: Math.random(),
              })),
            },
          ],
        },
        options: {
          showOutline: false,
          showGraticule: false,
          plugins: {
            legend: {
              display: false,
            },
          },
          scales: {
            xy: {
              projection: "equirectangular",
            },
          },
        },
      }
    );
  });
```

**Comment by thibaultzanini** [comment]
So, I find a way, but it's kind of hacky. I directly modified the topojson data.  

```   
fetch("https://unpkg.com/world-atlas/countries-50m.json")
  .then((r) => r.json())
  .then((data) => {
       data.transform.translate[0] = -191.5;
       data.bbox[0] = -191.5;
  });
```

![image](https://user-images.githubusercontent.com/3347451/176872524-628e92bd-69eb-4a09-b95a-3c0aa6e22181.png)

Does your library provide a better way? Thanks

**Comment by sgratzl** [comment]
you might find the `padding` option useful:

https://github.com/sgratzl/chartjs-chart-geo/blob/14e2b237490500fbf7dc5a10b49cc8c23fec2948/src/scales/ProjectionScale.ts#L80-L84

**Comment by thibaultzanini** [comment]
Unfortunately, it doesn't seem to work. 

<img width="961" alt="image" src="https://user-images.githubusercontent.com/3347451/177112508-191b9511-48fd-40a8-a6ba-f4963c91703a.png">

I tried to set the `padding` option, but no luck.

```
scales: {
  xy: {
    projection: "equirectangular",
    padding: -30,
  },
},

// OR

scales: {
  xy: {
    projection: "equirectangular",
    padding: {
        top: 0,
        right: -30,
        left: -30,
        bottom: 0,
      },
  },
},
```
