### ISSUE TITLE
CommonJS or AMD dependencies Warning on Chart Geo Js

### ISSUE THREAD

**Issue by Thishonjoel** [sgratzl/chartjs-chart-geo#128]
I am using Chart Geo choropleth, but when i am trying to ng build its shows " 'chartjs-chart-geo'. CommonJS or AMD dependencies can cause optimization bailouts." would you help me how to solve this.

**Comment by sgratzl** [comment]
should be fixed with https://github.com/sgratzl/chartjs-chart-geo/releases/tag/v3.9.0
