### ISSUE TITLE
How to center my GeoChart

### ISSUE THREAD

**Issue by javisanz15** [sgratzl/chartjs-chart-geo#13]
Good afternoon!

I'm writing because I tried to implement the geochart in my app, following the germany codepen you have in one of the old open issues. It works totally fine but i find that it always stays on the left side of the canvas area. Would you know maybe how to solve something like this? 

![5mar1](https://user-images.githubusercontent.com/52543808/75988885-900ba400-5ef2-11ea-86ee-e6dfb3cba58d.PNG)

![5Mar2](https://user-images.githubusercontent.com/52543808/75988894-9437c180-5ef2-11ea-8c0e-c01ba3aa13da.png)

**Comment by javisanz15** [comment]
This is the method I use to create the chart, it is a little different as I am using Typescript, so I have to perform a few tricks to make it work.

`public createChart() {
    this.userProfileService.getGeoData('country').subscribe(data => {
      const regions = GeoChart.topojson.feature(data[0], data[0].objects.layer).features.filter(item => item.properties.NAME_0 === 'Germany');
      const countries = GeoChart.topojson.feature(data[1], data[1].objects.continent_Europe_subunits).features;
      const Germany: any = countries.find((d) => d.properties.geounit === 'Germany');

      const displayData = regions.map((d) => ({ feature: d, value: Math.random() }));


      const options: any = {
        maintainAspectRatio: true,
        showOutline: false,
        showGraticule: false,
        legend: {
          display: false
        },
        scale: {
          projection: 'mercator',
        },
      };

      const datasets: any = [{
        label: 'Regions',
        outline: [Germany],
        backgroundColor: (context) => {
          if (!context.dataIndex && context.dataIndex !== 0) {
            return null;
          } else {
            const value = context.dataset.data[context.dataIndex];
            return this.color('steelblue').lightness((value as any).value * 100).rgbString();
          }
        },
        data: displayData,
      }]


      this.chart = new Chart(this.chartRef.nativeElement.getContext("2d"), {
        type: 'choropleth',
        data: {
          labels: regions.map((d) => d.properties.NAME_1),
          datasets: datasets,
        },
        options: options,
      });

    });
  }`

**Comment by sgratzl** [comment]
can you provide me the TopoJson files that you used, such that I can play around with it on e.g. Codepen or Codesandbox?

**Comment by javisanz15** [comment]
This are the two Topojson files that i used, I also send you the method i use to retrieve them, in case it can give any additional information.

![6Mar3](https://user-images.githubusercontent.com/52543808/76066266-97cc5680-5f8d-11ea-9863-c30f3954375a.png)

**Comment by sgratzl** [comment]
fixed with https://github.com/sgratzl/chartjs-chart-geo/releases/tag/v1.1.4
