### ISSUE TITLE
Unable to hide map scale

### ISSUE THREAD

**Issue by lee-wilkins** [sgratzl/chartjs-chart-geo#131]
Hi

Referencing https://github.com/sgratzl/chartjs-chart-geo/issues/61 
and 
https://github.com/sgratzl/chartjs-chart-geo/blob/17132af15391fe3e7f2454ac49d8743b5a25abdc/samples/albersLegend.html#L44-L49

We want to hide the map scale completely. However the options to hide the scale do not work.

Version 3.8.1
Angular 14.0.5

Our current map. Showing the area in red that we expect to hide: 

![Screenshot 2022-08-15 at 11 53 42 PM](https://user-images.githubusercontent.com/19402472/184670053-31452ad4-18e3-44f5-9f09-2806329d6c63.png)

Chart Options:
`{
      scales: {
        xy: {
          projection: 'equalEarth', 
        },
        color: {
          display: false,
        },
      },
      plugins: {
        legend: {
          display: false,
        },
        tooltip: {
          enabled: true,
        },
      },
    };
`

Thanks!

**Comment by sgratzl** [comment]
you are using a bubble map thus the scale responsible for the color is called `size` not `color`

**Comment by lee-wilkins** [comment]
Hi @sgratzl - thanks so much for your fast response! 

We've also tried the size scale actually and also has no effect. Are we using it incorrectly?

`{
      scales: {
        xy: {
          projection: 'equalEarth', // ... projection method
        },
        size: {
          display: false,
        },
      },
      plugins: {
        legend: {
          display: false,
        },
        tooltip: {
          enabled: true,
        },
      },
    };
  }`

**Comment by sgratzl** [comment]
can you create a codepen or codesandbox to play around, please

**Comment by lee-wilkins** [comment]
Thanks @sgratzl - Please see codepen based on your existing examples on the homepage: https://codepen.io/lee-wilkins/pen/GRxwvdL

**Comment by stockiNail** [comment]
@lee-wilkins  Sorry if I'm jumping in the thread but the default id of size scale is `'r'`, therefore if you try in your codepen setting `scales.r.display: false` should work.

**Comment by lee-wilkins** [comment]
@stockiNail - perfect! Works like a charm

I've saved the codepen with the updated setting incase anyone else comes across this thread.

**Comment by sgratzl** [comment]
thx @stockiNail 

I always forget that I called it `r` and not `size`, see also https://github.com/sgratzl/chartjs-chart-geo/blob/b6b210c7737abb096447621f128e12f91643133d/samples/bubbleMapArea.html#L59-L61

**Comment by stockiNail** [comment]
@sgratzl maybe for version 4(because it will a breaking change) the scale id in the BubbleMap controller default could be changed in `size`. Choropleth is already using `color` as scale id for color scale. 
Also the projection scale in GeoController can be changed from `xy` to `projection`.
I'm not sure 100% (for me this means change my lib :worried:) but maybe is more user friendly.

**Comment by Amooryjubran** [comment]
How would we hide the map scale for the ```choropleth```  ?

**Comment by Amooryjubran** [comment]
> How would we hide the map scale for the `choropleth` ?

This got the job done for `choropleth ` ``` color: { display: false} ```

**Comment by ahmadmobaraki** [comment]
> How would we hide the map scale for the `choropleth` ?

For `chartjs-chart-geo` plugin, I was able to disable color scale by:
```js
options {
    scales {
        color {
             display: false     
        {
    }   
}
```
