### ISSUE TITLE
ChartGeo is not defined for 3.9.0 

### ISSUE THREAD

**Issue by Ronandt** [sgratzl/chartjs-chart-geo#132]
When I use version 3.9.0, ChartGeo is not defined. I am currently using 2.1.0 and ChartGeo works. 
![image](https://user-images.githubusercontent.com/49837565/184906857-727ef748-45b8-4950-ad73-a94060271d77.png)
![image](https://user-images.githubusercontent.com/49837565/184906975-4873ec88-fd4f-48c6-b50d-575ad00866c7.png)

**Comment by stockiNail** [comment]
@Ronandt maybe I'm wrong but from version 3.0.0-beta.1 this is the URL (not called Chart.geo.min.js): https://cdn.jsdelivr.net/npm/chartjs-chart-geo@3.9.0/build/index.umd.min.js

**Comment by sgratzl** [comment]
yes `https://cdn.jsdelivr.net/npm/chartjs-chart-geo@3.9.0` should also work just fine. 

Note that v3.X.? is only compatible with chart.js v3.X.?
