### ISSUE TITLE
How to hide color scale?

### ISSUE THREAD

**Issue by pawelbajgrowicz** [sgratzl/chartjs-chart-geo#137]
How to remove marked color scale?

![image](https://user-images.githubusercontent.com/86665196/191985850-e52d08ca-40df-404a-93cb-6f3ed1a5864a.png)

**Comment by stockiNail** [comment]
@pawelbajgrowicz you could disable the `color` scale as following:

```javascript
options: {
  ...
  scales: {
    color: {
      display: false
    } 
  }
}
```
