### ISSUE TITLE
How to display only a certain area of a world map?

### ISSUE THREAD

**Issue by b8** [sgratzl/chartjs-chart-geo#138]
I have to display some selected countries of the world. The selection would change on each page load. I'd like to show a world map using all countries as outline but clip the entire chart so that only the part of the chart is shown that contains the selected countries. E.g. when Switzerland, Germany and Austria is selected, only western Europe should be shown. Many European countries are too small when I show a world map in a 516x280px div... (I currently use the `naturalEarth1` projection and `world-atlas/countries-110m.json` data).

I've tried to calculate which outline countries have to be in my chart because `chartjs-chart-geo` automatically "zooms" into the countries in the outline. But this looks sometimes strange on the edges because I only include/exclude full countries.
I'd expect a possibility to clip the area to the countries (features) in the datasets (not the outline) or to specify the area coordinates that should be visible.

Is there any other possibility?

**Comment by sgratzl** [comment]
e.g. https://codepen.io/sgratzl/pen/jOxYMJY

**Comment by b8** [comment]
Thanks. That's what I tried but I'm not so happy with the result. E.g. it results in charts like this:
![grafik](https://user-images.githubusercontent.com/171125/192474619-5b29396c-3a6d-4be8-9b06-d4ba23cdc536.png)
It seems like Israel is an isle because some African countries are missing, also North America. But if I include them, it will zoom out and the relevant countries are getting smaller.

I'd like something like this (just regarding the outlines of the countries):
![grafik](https://user-images.githubusercontent.com/171125/192476762-83221814-beb2-4106-8d8c-3111272682a3.png)

**Comment by sgratzl** [comment]
stale closing
