### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by braveheart-star** [sgratzl/chartjs-chart-geo#142]
When I use this library in the Next.js for bubbleMap, there is building issue.
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/.../[project]/node_modules/d3-geo/src/index.js
require() of ES modules is not supported.
require() of /Users/.../[project]/node_modules/d3-geo/src/index.js from /Users/.../[project]/node_modules/chartjs-chart-geo/build/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/.../[project]/node_modules/d3-geo/package.json.

**Comment by luckyxhu** [comment]
so am i

**Comment by sgratzl** [comment]
I honesty lost track which framework/builder/service uses which package.json field these days:

https://github.com/sgratzl/chartjs-chart-geo/blob/d97f017138984d7fc7e37976b77025ee738bca7b/package.json#L27-L33

e.g. I don't define yet `type: module`

**Comment by sgratzl** [comment]
re de-geo: I had to upgrade d3-geo along with d3-color to fix a major security vulnerability. However, d3 in these recent versions are only module based and that creates a lot of headache

**Comment by braveheart-star** [comment]
there is no solution?
I hope to have the bug fixed asap.

**Comment by sgratzl** [comment]
atm I would recommended to downgrade to the previous version https://github.com/sgratzl/chartjs-chart-geo/releases/tag/v3.9.0

**Comment by braveheart-star** [comment]
it's not working with all versions.

**Comment by sgratzl** [comment]
4.0.0 is start being an ESM module
