### ISSUE TITLE
Tooltip for multiple datasets doesn't work after page refresh

### ISSUE THREAD

**Issue by atadeuccislideworks** [sgratzl/chartjs-chart-geo#143]
When using multiple datasets, the tooltip after a page refresh will only show the information of the first dataset.

**To Reproduce**

Codesandbox: https://codesandbox.io/s/react-chartjs-2-map-forked-6hyh0g?file=/src/geo-map.tsx

1. Go to the codesandbox above and the tooltip will only show for the first dataset. 
![image](https://user-images.githubusercontent.com/108531792/196287175-9fc20506-a86c-4231-9f64-dad2ac73d3da.png)

2. Change the name of any dataset and after it hot-reloads, the tooltips for both datasets should show as expected
![image](https://user-images.githubusercontent.com/108531792/196286505-45423c09-4f0e-4d2a-9049-fffc1d6e83ba.png)

3. Refresh the codesandbox, now the tooltip will only show for the first dataset. 
![image](https://user-images.githubusercontent.com/108531792/196286694-bc412632-5cb3-4dc0-8791-6e65f467cb06.png)

**Expected behavior**

Tooltip should show for all datasets, even after page refresh.

An example of it working but in Angular
https://codesandbox.io/s/angular-brazil-map-forked-ue0h05?file=/src/app/app.component.ts

- Version: 3.9.0
- Browser: All

**Comment by sgratzl** [comment]
this plugin doesn't control how the tooltips are computed. That is chart.js. Not sure how it computes everything for two charts on top of each other. 

This plugin only provides the required methods such that the tooltip position can be computed: 

https://github.com/sgratzl/chartjs-chart-geo/blob/d97f017138984d7fc7e37976b77025ee738bca7b/src/elements/GeoFeature.ts#L81-L125

**Comment by atadeuccislideworks** [comment]
Thanks for the reply!

Damn I guess then the issue is with chartjs-react since I got it working with vanilla js.

**Comment by atadeuccislideworks** [comment]
For anyone who might come into the same issue, my solution was to hack it a little.

I used only one dataset, and added the raw information for that state inside the data object
```
data: data.map((d: any) => ({
  feature: d,
  value: 60,
  raw: [50, 10],
}))
```

Then I eddited the tooltip to get that information
```
plugins: {
  tooltip: {
    callbacks: {
      label: (context: any) => {
        return [
                  context.element.feature.properties.name,
                  `Total ${context.formattedValue}`,
                  `Dataset 1 ${context.raw.raw[0]}`,
                  `Dataset 2 ${context.raw.raw[1]}`
          ];
      },
    },
  },
},
```
Codesandbox with example 'fix':
https://codesandbox.io/s/react-chartjs-2-map-fix-multiple-datasets-ek5hwc?file=/src/geo-map.tsx:1561-1805
