### ISSUE TITLE
Support for Chart.js 4.x

### ISSUE THREAD

**Issue by pawel-omniaz** [sgratzl/chartjs-chart-geo#147]
Hi,

I tried to install this package with latest version of Chart.js (v4.0.1) but it requires ^3.9.1 :/

Would it be hard to update this package? Or do you have plans to do so?

Best regards

EDIT:
From my tests it works with chart.js v4.x, there wasn't that much changes anyway in latest version. Maybe it's enough to change dependency to allow v3 and v4?

**Comment by sgratzl** [comment]
blocked by https://github.com/chartjs/Chart.js/issues/10945

**Comment by pawel-omniaz** [comment]
Understood, thanks for info.

**Comment by sgratzl** [comment]
first version in https://github.com/sgratzl/chartjs-chart-geo/releases/tag/v4.0.1
