### ISSUE TITLE
Tooltips not showing value in choropleth

### ISSUE THREAD

**Issue by javisanz15** [sgratzl/chartjs-chart-geo#15]
Hi!

I was checking out the choropleth example you have in sandbox:

https://codepen.io/sgratzl/pen/GRKLQBw

Because I realized I found the same problem in my code, as the tooltips that appear when you hover on each region in this case show the color and the label but not the value. This doesn't happen in the bubble one and I cannot understand what is the reason for that.

Thanks for everything in advance.

**Comment by sgratzl** [comment]
the default bubble controller has a customized tooltip implementation: 

https://github.com/chartjs/Chart.js/blob/2df6986fbe466c1a4009014bf7ed3b91442f97ad/src/controllers/controller.bubble.js#L35-L38

you might try to also add a custom one

**Comment by javisanz15** [comment]
Works perfectly! Thank you so much
