### ISSUE TITLE
Version 4.0.1 release statement not clear

### ISSUE THREAD

**Issue by stockiNail** [sgratzl/chartjs-chart-geo#151]
Reading the version 4.0.1 of the controller, there is the following statement (with a typo;) ):

 * require `aixs: 'r'` property when configuring one of the custom scales (projection, size, color)

As far as I can see, but maybe I'm wrong, there isn't any need to set `axis: 'r'`. axis: 'x' seems to be ok. 
let me know if I'm wrong.

**Comment by sgratzl** [comment]
yeah `axis: 'x'` is better, I updated the release notes. thx
