### ISSUE TITLE
Canada + Provinces

### ISSUE THREAD

**Issue by ilrein** [sgratzl/chartjs-chart-geo#16]
Thanks for the awesome plugin!

I am struggling to get a map of just Canada + Provinces.

I have some code that looks like this:

```js
<template>
  <canvas id="canvas"></canvas>
</template>

<script>
import 'chart.js';
import 'chartjs-chart-geo';

import countriesTopoJson from "world-atlas/countries-50m.json";

const countries = ChartGeo.topojson.feature(
  countriesTopoJson,
  countriesTopoJson.objects.countries,
).features;

// console.log(countries);

export default {
  name: 'CATest',
  mounted() {
    const Canada = countries.find((d) => d.properties.name === 'Canada');

    const chart = new Chart(document.getElementById('canvas').getContext('2d'), { // eslint-disable-line
      type: 'choropleth',
      data: {
        labels: countries.map((d) => d.properties.name),
        datasets: [{
          label: 'States',
          outline: [Canada],
          backgroundColor: (context) => {
            if (context.dataIndex == null) {
              return null;
            }
            const value = context.dataset.data[context.dataIndex];
            return new Color('steelblue').lightness(value.value * 100).rgbString();
          },
          data: countries.map((d) => ({ feature: d, value: Math.random() })),
        }]
      },
      options: {
        legend: {
          display: false
        },
        scale: {
          projection: 'mercator'
        }
      }
    });
  },
}
</script>

<style scoped>
#canvas {
  width: 100vw;
  height: 100vh;
}
</style>
```

Which results in:

<img width="1327" alt="Screen Shot 2020-03-31 at 2 44 46 PM" src="https://user-images.githubusercontent.com/5523014/78063434-34500180-735e-11ea-8f68-e0cb4e3a381a.png">

How can I strip all countries that are not Canada, and also highlight all the provinces?

**Comment by sgratzl** [comment]
you have to look for a proper topojson file focusing on the provinces of Canada. A quick google search came up with the following resuts:

https://gist.github.com/Brideau/2391df60938462571ca9
https://github.com/Anujarya300/bubble_maps/blob/master/data/geography-data/canada.topo.json

based on the second one I created:

https://codepen.io/sgratzl/pen/YzXgQWz?editors=0010

**Comment by ilrein** [comment]
Ah, you're a lifesaver @sgratzl !

thanks so much :D
