### ISSUE TITLE
Crimea is rendered as part of russia

### ISSUE THREAD

**Issue by sorm-at** [sgratzl/chartjs-chart-geo#169]
When I...

Highlight  russia, I see Crimea is rendered as part of it. When Ukraine is highlighted , it is visibly without Crimea.

When russia is highlighted , there must be no Crimea as part of it, and when Ukraine is highlighted, Crimea must part of Ukraine 

**Screenshots**

![image](https://user-images.githubusercontent.com/81250097/230348883-937e8488-5912-474e-b1ca-47241524f4c7.png)

**Context**

- Version: v3
- Browser: Chrome Version 111.0.5563.147

**Additional context**

**Comment by sgratzl** [comment]
this plugin doesn't provide the maps (geojson files) that are being rendered, it is just rendering what is given. I don't have an influence which maps users are using. I would reach out to the owner who provided your geojson file about this.

**Comment by sorm-at** [comment]
Hello @sgratzl , 

Thank you! Do you use https://www.npmjs.com/package/world-atlas as source ?

**Comment by sgratzl** [comment]
I don't know which example you were using. but yes the examples in this repository are referencing https://cdn.jsdelivr.net/npm/world-atlas/countries-50m.json such as https://github.com/sgratzl/chartjs-chart-geo/blob/main/samples/earth.html

**Comment by sorm-at** [comment]
> I don't know which example you were using. but yes the examples in this repository are referencing https://cdn.jsdelivr.net/npm/world-atlas/countries-50m.json such as https://github.com/sgratzl/chartjs-chart-geo/blob/main/samples/earth.html

I use https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json 

Thank you for information!

**Comment by DaniilRyb** [comment]
реально https://github.com/sgratzl/chartjs-chart-geo/issues/169#issuecomment-2061086036
