### ISSUE TITLE
How to show legends for the map

### ISSUE THREAD

**Issue by filipesaraiva** [sgratzl/chartjs-chart-geo#17]
I am using chartjs-chart-geo to show some [maps of COVID-19 in Brazil](http://ccsl.ufpa.br/covid-19/). I don't find how to put legends in the maps. Is there any way to do it?

**Comment by sgratzl** [comment]
not at the moment. The main problem is that the color scale is just indirectly defined via the `backgroundColor`.

**Comment by filipesaraiva** [comment]
In fact, but if we have an `option` to do it manually, that could be a possible workaround. Maybe, manually add the color + label for the legend in order to be presented at the map, with all `click`actions disabled, it can be a reasonable alternative.

Thanks for all your work with this library, @sgratzl!

**Comment by sgratzl** [comment]
I'm currently working on how to render a legend and also deal with the coloring. In the meanwhile you could draw a legend by yourself, e.g using a plugin that just renders what you want. e.g. https://observablehq.com/@d3/color-legend renders a bunch of good legends which you can use as an inspiration.

**Comment by sgratzl** [comment]
current progress (to be released soon):

![image](https://user-images.githubusercontent.com/4129778/78814649-44578900-79cf-11ea-8c66-463ec28e3c4f.png)

![image](https://user-images.githubusercontent.com/4129778/78814663-4cafc400-79cf-11ea-9f68-9083281ef92d.png)

**Comment by filipesaraiva** [comment]
Amazing job @sgratzl, thank you a lot! I will test the beta release ASAP! :heart_eyes:
