### ISSUE TITLE
bubbleMap with countries

### ISSUE THREAD

**Issue by remyfrd** [sgratzl/chartjs-chart-geo#175]
Hi,

I try to create a bubbleMap on all countries not like in the example who is only for US states. 
Do you have any idea to make this ?

I think my problem is that I do not found file with all world capitals like  https://gist.githubusercontent.com/mbostock/9535021/raw/928a5f81f170b767162f8f52dbad05985eae9cac/us-state-capitals.csv

Thanks for your help

**Comment by brian-patrick-3** [comment]
@remyfrd Did you come up with a solution for this? I'm also looking to build a sample world bubbleMap.

**Comment by sgratzl** [comment]
a quick search lead to https://gist.github.com/ofou/df09a6834a8421b4f376c875194915c9
