### ISSUE TITLE
error in vite

### ISSUE THREAD

**Issue by nemesisKO** [sgratzl/chartjs-chart-geo#177]
The requested module '/node_modules/.vite/deps/chartjs-chart-geo.js?v=fe996f1c' does not provide an export named 'default'

any idea how to fix it?

**Comment by sgratzl** [comment]
yes there is no default export:

https://github.com/sgratzl/chartjs-chart-geo/blob/main/src/index.ts

not sure how you import the library

**Comment by nemesisKO** [comment]
i imported just like documentation
`import { Chart , registerables} from 'chart.js';
import { ChoroplethController, GeoFeature, ColorScale, ProjectionScale } from 'chartjs-chart-geo';
Chart.register(ChoroplethController, GeoFeature, ColorScale, ProjectionScale);`

im dont know how to use map. the documentation said
`fetch('https://unpkg.com/world-atlas/countries-50m.json').then((r) => r.json()).then((data) => {
      const countries = ChartGeo.topojson.feature(data, data.objects.countries).features;`
      
      but where is ChartGeo. can you plaese show me a full example with using npm imports way. the codepen examples doesnt suite my project
