### ISSUE TITLE
choropleth and bubbleMap at the same time?

### ISSUE THREAD

**Issue by gihco** [sgratzl/chartjs-chart-geo#18]
Hi,
It seems that it will not be possible to have choropleth and bubbles at the same time as both are represented by its own chart type, right?
Is there something I'm missing?
Is this something you plan to add for the future?
Many thanks!

**Comment by sgratzl** [comment]
it seems to work as in https://codepen.io/sgratzl/pen/XWmpbZQ?editors=0010

**Comment by gihco** [comment]
Many thanks for the quick and profound reply!

I have a use case for that (which makes sence I believe) which currently uses Datamaps (https://datamaps.github.io/) based on d3/svg. However, that lib is no longer maintained and I use chartjs anyway already in the same project.
Will no look into how far I get with animations, pan/zoom, performance, and HTML-based tooltips

**Comment by anupam42** [comment]
Hi,
I am looking something like choropleth and bubbleMap in one 
Because i will be having choropleth map as parent and how to map coordinate using bubbleMap
Ex: World map and show affected area with bubbleMap with coordinates

**Comment by sgratzl** [comment]
does the background map shows any data or just the outline of the world/countries for reference?

**Comment by anupam42** [comment]
Background just the outline of world map for reference and inside that i want to show coordinates for particular countries.
For Example i have attached image.

Thanks
<img width="447" alt="Screenshot 2020-05-14 at 1 04 16 PM" src="https://user-images.githubusercontent.com/16332264/81906256-977eb600-95e3-11ea-89b1-7552c5567753.png">

**Comment by sgratzl** [comment]
sounds more like a regular bubbleMap where they outline has a background color. 

similar to https://codepen.io/sgratzl/pen/vYNzOYr?editors=0010

**Comment by anupam42** [comment]
Its just bubbleMap can i do same with choropleth map ?
