### ISSUE TITLE
How to have tooltip when no legend is shown

### ISSUE THREAD

**Issue by bhall2001** [sgratzl/chartjs-chart-geo#191]
I have the following question...

I would like not show the legend on a choropleth but still have the tooltips show. I have not been able to figure out how to make that happen with v4.

In the attached code sandbox I have set the legend to false which also seems to disable the tooltips on the states.
https://codepen.io/bhall2001/pen/QWJYOBY

Browser: Version 115.0.5790.110 (Official Build) (64-bit) on Windows 10

Thanks in advance for you help.

**Comment by sgratzl** [comment]
try `display: false` instead of `legend: false`

**Comment by bhall2001** [comment]
That works. Thank you for the super quick response!!!!!!!!!!!
