### ISSUE TITLE
Choropleth doesn't appear

### ISSUE THREAD

**Issue by MalcolmBrt** [sgratzl/chartjs-chart-geo#195]
I can't get my choropleth map to appear in my canvas. I must surely be wrong somewhere but I don't know where, I copied line for line an example that worked with the map of the United States. I think I'm doing something wrong but I can't figure out what.

**Screenshots / Sketches**
https://codepen.io/MalcolmBrt/pen/PoXeWdX

**Context**

- Version: 4.2.5
- Browser: Brave

**Comment by sgratzl** [comment]
the default projection is `albersUsa` which is optimized for showing the US. You have to specify a different projection method like

```
scales: {
        projection: {
          axis: 'x',
          projection: 'equalEarth',
        },
}
```

**Comment by MalcolmBrt** [comment]
Thanks, it works. So many hours wasted just because of that 😭
