### ISSUE TITLE
Large values get cut off in choropleth chart

### ISSUE THREAD

**Issue by spl1nes** [sgratzl/chartjs-chart-geo#199]
When I use large numeric values in the choropleth chart the label gets cut off at the edge.

**To Reproduce**

Use large numbers as values. 

**Expected behavior**

Have the label move over.

**Screenshots**

![273669180-a87289eb-72b4-4a42-926c-f3d54ea3a880](https://github.com/sgratzl/chartjs-chart-geo/assets/5759397/957ecb2d-fd87-4c6a-a3da-100ea8bcaec2)

**Context**

- Version: only tested with 4.*
- Browser: firefox

**Comment by sgratzl** [comment]
you can adapt the width of the legend: https://github.com/sgratzl/chartjs-chart-geo/blob/52a9f3dffbf6114047f5db9a7c0bf4517ee1114e/src/scales/LegendScale.ts#L52-L58

**Comment by SureshS13** [comment]
@sgratzl 

> you can adapt the width of the legend:
> 
> [chartjs-chart-geo/src/scales/LegendScale.ts](https://github.com/sgratzl/chartjs-chart-geo/blob/52a9f3dffbf6114047f5db9a7c0bf4517ee1114e/src/scales/LegendScale.ts#L52-L58)
> 
> Lines 52 to 58 in [52a9f3d](/sgratzl/chartjs-chart-geo/commit/52a9f3dffbf6114047f5db9a7c0bf4517ee1114e)
>      /** 
>       * how wide the scale is, i.e., for a horizontal scale the height 
>       * if a value < 1 is given, is it assume to be a ratio of the corresponding 
>       * chart area 
>       * @default 50 
>       */ 
>      width: number;

How can we make this change in JS if we are using the index.umd.min.js build?
