### ISSUE TITLE
Mercator projection?

### ISSUE THREAD

**Issue by theianjohnson** [sgratzl/chartjs-chart-geo#2]
Do you support multiple types of projections for the world map? And are there projections without, for example, lat/long lines?

**Comment by sgratzl** [comment]
re without lines: -> see the `graticule` option
re projection methods -> you can specify the method used as part of the scale options, see https://github.com/sgratzl/chartjs-chart-geo#scales, you should be able to access of D3's https://github.com/d3/d3-geo#projections projection methods

see also: https://codepen.io/sgratzl/pen/qBBvRoq?editors=0010

**Comment by theianjohnson** [comment]
That is awesome, thank you! Is there any way to also leave off Antarctica (or exclude certain countries) and for the United States _only_, show all the states and have those have their own values?

**Comment by sgratzl** [comment]
each feature object represent a country or a state. Thus, you can just filter them out. e.g. 

```js
const subset = countries.filter((f) => f.properties.name !== 'Antarctica');
```

**Comment by theianjohnson** [comment]
Super easy 🙏 Is there any way to get the states displaying for the United States?

**Comment by sgratzl** [comment]
>  Is there any way to get the states displaying for the United States?

like that? https://codepen.io/sgratzl/pen/qBBvRoq?editors=0010

**Comment by theianjohnson** [comment]
You're a rockstar man, that's exactly it, thanks so much!
