### ISSUE TITLE
Can't understand how to use in JSX

### ISSUE THREAD

**Issue by syorito-hatsuki** [sgratzl/chartjs-chart-geo#200]
Can't found any tutorial for `TypeScript` or `react-chartjs-2` integration
![image](https://github.com/sgratzl/chartjs-chart-geo/assets/33298273/0435bb42-5a65-4290-ae0f-f483bc27b7e8)

**Comment by sgratzl** [comment]
this plugin is an extension to chart.js which is a Vanilla JavaScript library. I don't have experience how other libraries are wrapping chart.js such that it can be used in React, Vue, Svelte, ...

**Comment by ritesh83** [comment]
Thanks @sgratzl for this awesome library. I created an example with React recently https://github.com/ritesh83/chartjs-chart-geo-react-example. Hope its useful for other devs.
