### ISSUE TITLE
How to use bubble map with longitude and latitude

### ISSUE THREAD

**Issue by Dan-Veinberg** [sgratzl/chartjs-chart-geo#202]
Can someone give me an example on how to use bubblemap with longitude and latitude values for the whole world? Is there a way to do it without use typescript? 
Also can you answer the following questions:
1. I also keep an error that the map needs to be destroyed before being created. I am using React.js. 
2.  How to update map with new data? 

Thank you so much. I am have been trying to create a Bubble Map world map with longitude and latitude for several weeks now without success. 
My Code So far:

`useEffect(()=>{`
```
` fetch('https://unpkg.com/world-atlas@2.0.2/countries-50m.json')
    .then((r) => {
      console.log(r.json().then((datapoint)=>{
        const countries = ChartGeo.topojson.feature(datapoint,datapoint.objects.countries).features
        console.log(countries)
```
        
        const chart = new Chart(document.getElementById("canvas").getContext("2d"),{
          type: 'bubbleMap',
          data: {
            labels: countries.map((d) => d.properties.name),
            datasets: [
              {
                label: 'States',
                outline: countries,
                data: countries.map((d) => ({
                  value: 10,
                  feature: d
                })),
              },
            ],
          },
          options: {
            showOutline: true,
            showGraticule: false,
            plugins: {
              legend: {
                display: false,
              },
            },
            scales: {
              xy: {
                projection: 'equalEarth'
              },
            }
          },
        });

      }))
    
     
      })

`},[])``

**Comment by sgratzl** [comment]
have you looked at https://www.sgratzl.com/chartjs-chart-geo/examples/bubbleMap.html with https://github.com/sgratzl/chartjs-chart-geo/blob/main/docs/examples/data/us-capitals.json

**Comment by Dan-Veinberg** [comment]
Thank you for answering. How do I just do bubbles for longitude and latitude instead of states?

**Comment by sgratzl** [comment]
what do you mean? the referenced example uses the referenced json which contains long/lat for the US capitals and that's where the bubbles are shown.

**Comment by Dan-Veinberg** [comment]
Okay I see now. I will try it out. Thank for your help.
