### ISSUE TITLE
Samples on Readme doesn't work, 404 for https://github.com/sgratzl/chartjs-chart-geo/tree/main/samples

### ISSUE THREAD

**Issue by zackees** [sgratzl/chartjs-chart-geo#206]
Samples on Readme doesn't work, 404 for https://github.com/sgratzl/chartjs-chart-geo/tree/main/samples

**To Reproduce**

See readme link to samples

**Expected behavior**

**Screenshots**

**Context**

- Version:
- Browser:

**Additional context**

**Comment by sgratzl** [comment]
the main documentation has moved to https://www.sgratzl.com/chartjs-chart-geo/

**Comment by zackees** [comment]
Can the readme be updated?

**Comment by sgratzl** [comment]
should be
