### ISSUE TITLE
Problem with colorscale

### ISSUE THREAD

**Issue by jmrMachado** [sgratzl/chartjs-chart-geo#21]
I'm having a problem with the colorscale. The colorscale doesn't show. I used it like this:

```js
const chart = new Chart(document.getElementById("map").getContext("2d"), {
        type: 'choropleth',
        data: {
          labels: distritosPT.map((d) => d.properties.name),
          datasets: [{
            label: 'Distritos',
            outline: distritos2,
            backgroundColor: (context) => {
              if (context.dataIndex == null) {
                return null;
              }

              const value = context.dataset.data[context.dataIndex];
              return new Color('#78C2AD').blackness(value.value * 100).rgbString();
            },
              //data: distritos2.map((d) => ({feature: d, value: dict[d.properties.name]})),
              data: distritosPT.map((d) => ({feature: d, value: orgValues(d.properties.name)})),
          }]
        },
        options: {
          showOutline: true,
          legend: {
            display: false
          },
          scale: {
            projection: 'mercator'
          },
          **geo: {
            colorScale: {
              display: true,
              position: 'top',
              quantize: 10,
              legend: {
                position: 'top-right',
              },
            },
          },**
          tooltips: {
            callbacks: {
                afterLabel: function(tooltipItem, data) {
                  var distrito = data['labels'][tooltipItem['index']];
                  return "Union Organizations: " + dict[distrito];
                }
            }
          }
        }
      });
```

Hope you can help me.

Thank you.
![map](https://user-images.githubusercontent.com/25959790/84803125-77368280-aff9-11ea-95b7-4cdb7d5ccf6b.PNG)

**Comment by sgratzl** [comment]
which version of the library are you using?

**Comment by jmrMachado** [comment]
I'm using the Chart.geo.js and the Chart.bundle.js (version 2.9.3). I got those files from this repository some months ago and used them in my project. At that time, there was no option for colorscales. Do I need to generate those updated .js files? How can I do that?

**Comment by sgratzl** [comment]
I see, please use the latest stable version: https://github.com/sgratzl/chartjs-chart-geo/releases/tag/v2.1.0. Moreover, when you are using this version you can get rid of 

```
backgroundColor: (context) => {
              if (context.dataIndex == null) {
                return null;
              }

              const value = context.dataset.data[context.dataIndex];
              return new Color('#78C2AD').blackness(value.value * 100).rgbString();
            }
```

since it will be done for you with the color scale

**Comment by jmrMachado** [comment]
Thank you very much. How can I choose the range of values associated to the llegend of the colorscale? My biggest value is 222 but the colorscale ends at value 400.

**Comment by jmrMachado** [comment]
Like this?

geo: {
            colorScale: {
              display: true,
              interpolate: 'BrBG',
              position: 'top',
              quantize: 10,
              legend: {
                position: 'top-right',
                ticks: {
                  min: 0,
                  max: 250
                  
                }
              },
            },
          }

**Comment by sgratzl** [comment]
no the `ticks` should be directly within `colorScale`

**Comment by jmrMachado** [comment]
Thank you very much for your help and this very useful project.

**Comment by sgratzl** [comment]
you're welcome
