### ISSUE TITLE
Pacific Centered World Map.

### ISSUE THREAD

**Issue by bryanrscott** [sgratzl/chartjs-chart-geo#211]
Display the world map rotated 180 degrees, so that the pacific ocean is in the middle

**User story**

Sometimes the world is pacific focused.

**Additional context**

This issue on the d3 projections (https://github.com/d3/d3-geo/issues/285) suggests using rotate.  how do you access the projection to do?

**Comment by sgratzl** [comment]
the projection option: https://github.com/sgratzl/chartjs-chart-geo/blob/fbed8d1/src/scales/ProjectionScale.ts#L54 allows you use one of the predefined d3-geo ones or pass in a custom projection object. So, you should be able to create a new projection instance (e.g. d3.geoMercator()` then then call the rotate function before passing the object as the projection argument to the chart
