### ISSUE TITLE
Small countries as circles in choropleth map?

### ISSUE THREAD

**Issue by PMCS64** [sgratzl/chartjs-chart-geo#212]
In the below example, the country 442 being Luxembourg, it is impossible to see in the map the value of that country since it is a tiny country. Some mappers have fixed that problem by putting a small circle on top of smaller countries like the map below.

# What I would like

Note how the smaller countries have been replaced by circles.

![https://upload.wikimedia.org/wikipedia/commons/0/00/British_Overseas_Territories_and_Crown_Dependencies.svg](https://upload.wikimedia.org/wikipedia/commons/0/00/British_Overseas_Territories_and_Crown_Dependencies.svg)

# What I have done

```javascript
const countries_data = {"442": 104242, "036": 249530};

fetch('https://unpkg.com/world-atlas/countries-50m.json')
  .then((r) => r.json())
  .then((data) => {
    const countries = ChartGeo.topojson.feature(data, data.objects.countries).features;

    // Match countries in the chart data with the countries_data and assign values
    countries.forEach((d) => {
      const countryCode = d.id;
      const countryValue = countries_data[countryCode];
      d.properties.value = countryValue ? countryValue : 0;
    });

    const chart = new Chart(document.getElementById("canvas").getContext("2d"), {
      type: 'choropleth',
      data: {
        labels: countries.map((d) => d.properties.name),
        datasets: [{
          label: 'Countries',
          data: countries.map((d) => ({
            feature: d,
            value: d.properties.value,
          })),
        }]
      },
      options: {
        showOutline: true,
        showGraticule: true,
        plugins: {
          legend: {
            display: false
          },
        },
        scales: {
          projection: {
            axis: 'x',
            projection: 'equalEarth'
          }
        }
      }
    });
  });

```

**Comment by sgratzl** [comment]
sorry I misunderstood your question. while your solution sounds hacky, I don't think there is a way around it since this library just renders a map with the given geo shapes. As you figured out when you manipulate the shape you can achieve your desired effect.

**Comment by PMCS64** [comment]
Sounds good - just didn't know if there was any map or any code part of chartjs-chart-geo that might have had implemented it already somehow. Thanks for the quick replies. Feel free to mark as closed.
