### ISSUE TITLE
Canvas size is greater than map width?

### ISSUE THREAD

**Issue by carr1514** [sgratzl/chartjs-chart-geo#213]
When i render a chart out using chart-geo the canvas width is much larger than the actual map itself? causing it to spill out containers etc.

![image](https://github.com/sgratzl/chartjs-chart-geo/assets/51206886/9df77a96-8186-4ebd-bc50-393590eec472)

`{
                type: 'choropleth',
                data: {
                    datasets: [{
                        label: 'Countries',
                        data: [],
                        borderColor: 'rgba(255, 99, 132, 1)',
                        borderWidth: 1,
                        hoverBackgroundColor: 'rgba(255, 99, 132, 0.4)',
                        hoverBorderColor: 'rgba(255, 99, 132, 1)',
                        backgroundColor: []
                    }]
                },
                scales: {
                    projection: {
                        axis: 'x',
                        projection: 'naturalEarth1',
                        projectionScale: 1.2,
                        projectionOffset: [0, 30],
                    },
                    color: {
                        axis: "color",
                        display: false
                    }
                },
                layout:
                    {
                        autoPadding: false,
                    },
                plugins: {
                    htmlLegend: {
                        containerID: 'legend-container',
                    },
                    legend: {
                        display: false,
                    }
                },
                maintainAspectRatio: false,
                responsive: true,
                showOutline: false,
                showGraticule: false,
            };`

This is the options used, latest chart-geo and chart.js

**Comment by sgratzl** [comment]
this is a plugin for chart.js, it doesn't determine or manipulates the given chart size but only fits the map into the given container.
