### ISSUE TITLE
Any plan for support chart v4~

### ISSUE THREAD

**Issue by muf** [sgratzl/chartjs-chart-geo#216]
Hi,
I seems that you currently do not support v4 or later versions. (https://github.com/sgratzl/chartjs-chart-geo/issues/147)

However, I would like to know if you are considering supporting v4 or later versions in the future.

Thank you for your time and consideration.

**Comment by sgratzl** [comment]
what do you mean? since 4.x of this plugin it requires v4 of chart.js
