### ISSUE TITLE
How to do a bubbleMap using the world

### ISSUE THREAD

**Issue by onel** [sgratzl/chartjs-chart-geo#218]
I went through the example and I was looking for a way to combine the Bubble map but using the world map.
Is that possible? Any examples for this case? 

I tried combining `type: 'bubbleMap'` with the options bubbleMap's codepen but it doesn't seem to work.

Also, I tried with different topojson files, but the API is not very clear what the format of those files should be.

Thanks

**Comment by sgratzl** [comment]
sure you can

you will need
 * long/lat for the points you want to render
 * change the projection to a word based one e.g. `mercator`, `equalEarth`
 * optionally have an `outline` which is a topojson file of the world

**Comment by catalinacalin7** [comment]
Can you please make a codepen with an example?
Thanks

**Comment by sgratzl** [comment]
random cities in  world:

https://codepen.io/sgratzl/pen/WNWojKq?editors=0010

![image](https://github.com/sgratzl/chartjs-chart-geo/assets/4129778/ac8acf1f-7303-45c4-8183-c3f22b7d447c)
