### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by onel** [sgratzl/chartjs-chart-geo#219]
I found some broken link:
- Options, uses this https://github.com/sgratzl/chartjs-chart-geo/blob/main/src/controllers/GeoController.ts#L221 but I don't think it's still valid
- the links on https://www.sgratzl.com/chartjs-chart-geo/ In the `API` section
https://www.sgratzl.com/chartjs-chart-geo/docs/api/classes/BubbleMapChart.html

**Comment by sgratzl** [comment]
fixed
