### ISSUE TITLE
chart.destroy() isn't destroying the chart

### ISSUE THREAD

**Issue by MrsNickalo** [sgratzl/chartjs-chart-geo#231]
When specifically using the Bubblemap, when I call chart.destroy(), it doesn't seem to be destroying the chart. When I create a new chart, I get this error below. I do not have the same issue when using the Choropleth chart or any other ChartJs charts. Any assistance would be appreciated.

_**ERROR Error: Uncaught (in promise): Error: Canvas is already in use. Chart with ID '2' must be destroyed before the canvas with ID 'MyChart' can be reused.
Error: Canvas is already in use. Chart with ID '2' must be destroyed before the canvas with ID 'MyChart' can be reused.**_

This is my code:
`createBubbleChart() {
		// we must destroy the existing chart before making a new one
		if(this.chart) {
			this.chart.destroy();
			this.chart = null as any;
		}
		this.chart = new Chart("MyChart", {
			type: 'bubbleMap', 
	    data: {
	      labels: this.zipcodeCoordinates.map((d) => d.description),
	      datasets: [{
	        outline: this.states,
	        outlineBackgroundColor: '#EAEAEA',
	        outlineBorderColor: 'black',
	        outlineBorderWidth: 1,
	        showOutline: true,
	        borderWidth: 1,
	        borderColor: 'black',
	        backgroundColor: '#990000',
	        data: this.zipcodeCoordinates,
	      }]
	    },
	    options: {
	      plugins: {
	        legend: {
	          display: false
	        },
	      scales: {
	        projection: {
	          axis: 'x',
	          projection: 'albersUsa',
	        },
	        size: {
						axis: 'x',
						display: false
					}
	      }
	    }
	  });
	}`

- Version: "chart.js": "^4.4.0", "chartjs-chart-geo": "^4.2.7"
- Browser: Chrome

**Comment by sgratzl** [comment]
can you provide a standalone example that I can use.

**Comment by MrsNickalo** [comment]
Will this work? This just creates an empty bubbleMap:
`createEmptyChart() {
		// we must destroy the existing chart before making a new one
		if(this.chart) {
			this.chart.destroy();
			this.chart = null as any;
		}
		this.chart = new Chart("MyChart", {
			type: 'bubbleMap', 
	    data: {
	      datasets: [{
	        outline: this.states,
	        outlineBackgroundColor: '#EAEAEA',
	        outlineBorderColor: 'black',
	        outlineBorderWidth: 1,
	        showOutline: true,
	        borderWidth: 1,
	        borderColor: 'black',
	        backgroundColor: '#990000',
	        data: [],
	      }]
	    },
	    options: {
	      plugins: {
	        legend: {
	          display: false
	        },
	      },
	      scales: {
	        projection: {
	          axis: 'x',
	          projection: 'albersUsa',
	        },
	        size: {
						axis: 'x',
						display: false
					}
	      }
	    }
	  });
	}`

**Comment by sgratzl** [comment]
I cannot reproduce it https://codepen.io/sgratzl/pen/BaedJmz?editors=0010

**Comment by MrsNickalo** [comment]
My application is an Angular application using Typescript. As such, I'm not referencing the HTML element like you are. In your Codepen, I see this:
`let elem = document.getElementById("canvas");`
And you pass that into the new Chart call:
`const createChart = (elem) => {
    return new Chart(elem, `
In my application, I am simply referencing the HTML element by its id in the call to new Chart:
`this.chart = new Chart("MyChart",`

I tried to set up a Codepen to demonstrate but was unable to get the TS and Angular stuff to work. Could the issue be that I am referencing the HTML element by id instead of getting the HTML element like you do?
And if that is the issue, why do I only encounter the error with "bubbleMap" and not with "choropleth"?

**Comment by MrsNickalo** [comment]
Actually, I don't think that's it because even doing it this way:
![image](https://github.com/sgratzl/chartjs-chart-geo/assets/54821996/dcfb2b04-07bb-495e-86e3-4b1f2295c304)

I still get the same error:
![image](https://github.com/sgratzl/chartjs-chart-geo/assets/54821996/f975caa5-01c9-44e0-bd5f-2a001956b77a)

**Comment by MrsNickalo** [comment]
By moving the elem variable out and making it a component variable, it appears to be working now. Thanks for the assistance.
