### ISSUE TITLE
Custom _getNormalizedValue for option interpolate

### ISSUE THREAD

**Issue by dieunq1001** [sgratzl/chartjs-chart-geo#251]
I'm having the following question...

I noticed that Interpolate will automatically normalize my value, which I do not want to. Is there anyway to custom my own _getNormalizedValue in interpolate or to not use it at all? Much appreciated.

- Version: ^3.10.0
- Browser: Firefox/Chrome

**Comment by sgratzl** [comment]
internally a color scale just a fancy way to get a background color: https://github.com/sgratzl/chartjs-chart-geo/blob/9aacf4a1f9910b51e908d18e3d8459cc414d0950/src/controllers/ChoroplethController.ts#L138. 

so you can just provide a custom backgroundColor and have access to all values.

**Comment by dieunq1001** [comment]
I have tried this method to custom backgrounds color for my dataset. However, I can not find out a way to custom ColorScale to match the background colors value. Is there a callback function like Legend to custom ColorScale ?

**Comment by sgratzl** [comment]
there isn't a way since the the scale interface used to normalize and generate the color is limited to giving only a numeric value
