### ISSUE TITLE
Map outline 

### ISSUE THREAD

**Issue by damienderoistecso** [sgratzl/chartjs-chart-geo#26]
I've started using this library to load dynamic data from an API on a choropleth map.

However, it seems as if I have to load 2 geo files to render the map as I want.

First I load the region file. In this case it for Ireland NUTS 3. Then I have to load the outline geo file which is all the countries in Europe and I find the feature for Ireland.

See my code here https://codepen.io/damienderoiste/pen/rNxqRJE

For my application to work, I need to only load the regional geo file which is retrieved from my API. Having to also load the appropriate outline file is a problem. 

Can you suggest any workaround? 

Thanks 
Damien

**Comment by sgratzl** [comment]
you can just set the list of your regions `regionsFeatures` as the outline. It might not be as efficient but should work.

**Comment by damienderoistecso** [comment]
Thanks, that worked!
