### ISSUE TITLE
Map rendering not right

### ISSUE THREAD

**Issue by damienderoistecso** [sgratzl/chartjs-chart-geo#27]
I'm trying to create a map from a topojson file I generated from shape files using mapshaper.org

Shape file got from got from here http://data-osi.opendata.arcgis.com/datasets/364949f58e65474e8018ebf27d78e55e_0.zip?outSR={%22latestWkid%22:2157,%22wkid%22:2157}

When I get my json and try and plot my data against it, it doesn't display correctly
See my codepen here https://codepen.io/damienderoiste/pen/rNxqRJE

I would appreciate it if you could take a look and see any issues. 

Thanks

**Comment by sgratzl** [comment]
how does it look when you reupload the exported file to mapshaper.org ? does it look as expected?

**Comment by damienderoistecso** [comment]
Yes, when I take the exported json file and re-upload it to mapshaper, it's as expected 

![image](https://user-images.githubusercontent.com/53211688/87985426-7d75be00-cad3-11ea-8445-f95acf8b3274.png)

**Comment by sgratzl** [comment]
I don't know which coordinate system this file is using and thus which projection method would be the appropriate one

**Comment by damienderoistecso** [comment]
> I don't know which coordinate system this file is using and thus which projection method would be the appropriate one

Thanks. I can get it to work with some files and not others so I need to figure out the coordinate system used and projection methods.

**Comment by damienderoistecso** [comment]
> I don't know which coordinate system this file is using and thus which projection method would be the appropriate one

Hi, sorry to re-open this but I'm wondering if you could help me on the same issue. I'm trying to figure out the projection method used in our files. I generated the GeoJOSN from a shape file and in the zip file that contained the .shp file there was also a .prj file. I think this might have some clues as to what the projection used might be a and thus help me figure out which projection method would be the appropriate one. The contents of the .prj file is as follows

GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433],METADATA["World",-180.0,-90.0,180.0,90.0,0.0,0.0174532925199433,0.0,1262]]

If anything here makes sense to you I'd appreciate any help.

Thanks
Damien

**Comment by youbao88** [comment]
Hi Damienderoistecso

When creating my choropleth, I think I run into the same problem like what you had. The map rendered is with a lot of lines but displayed perfectly in mapshaper.org. I think @sgratzl is correct and there is something related to projection. Here is my solution to this issue.

By using some software that could manipulate geospatial data (I used GeoPandas), you could change the projection from what you have now to 'EPSG: 4326'. Then, you change the 'projection' in your chartjs as 'mercator'. Hope this could work for your project.
