### ISSUE TITLE
Zooming in my cloropleth Geo Chart

### ISSUE THREAD

**Issue by javisanz15** [sgratzl/chartjs-chart-geo#28]
Hi! I am currently developing an app which renders a cloropleth map. However, as you can see in the image below the areas in the map can be pretty tiny so I am trying to implement a way to zoom in the map. I tried to use the plugin "chartjs-plugin-zoom" but I couldn't make it work at any kind. Would you have an example or know how could I get this feature to be added to my geo chart?

Thanks a lot.
Javier.

![image](https://user-images.githubusercontent.com/52543808/88464179-ff415f00-ceb8-11ea-8182-3050de6dead0.png)

**Comment by sgratzl** [comment]
I never tried that so far. Moreover, I guess more advanced map tools like mapbox are better suited for those cases
