### ISSUE TITLE
How to use custom projection? 

### ISSUE THREAD

**Issue by elvince** [sgratzl/chartjs-chart-geo#29]
Hi,

I spent many hours trying to create a projection that works out of the one you provided.

I wanted to use: https://github.com/seeschloss/francedom but I think it was made for an old version of D3.

So I found this one that can serve as a example:  https://github.com/rveciana/d3-composite-projections

If I use this package, set the projection to geoAlbersUSA in your sample, I can't get it work.
It claims that "fitwidth" is not a function.

I hope you can help me to use your plug-in.
Thanks,

**Comment by sgratzl** [comment]
I played around a bit: https://codepen.io/sgratzl/pen/oNbKBjz?editors=0010

yes the fitWidth was added in a later version which this package doesn't support. However, its implementation is quite easy but maybe not perfect.

**Comment by elvince** [comment]
Thanks for the feedback / support. It clearly helps to get a result.

**Comment by elvince** [comment]
Hi, sorry to necro this issue.

but as of v3, I can't get it working.
It was perfectly working on chart V2 with your V2 plug-in. Since I moved to V3, the projection is not working at all.
Any hints?

**Comment by sgratzl** [comment]
the projection logic hasn't changed. What has changed is the location where projections are customized. see also 

https://github.com/sgratzl/chartjs-chart-geo/blob/effcfe7dad5be67ddc6461c582bfba3420ce70ee/samples/earth.html#L40-L44

**Comment by elvince** [comment]
This is exactly what I've done.
In fact, when I use 'Mercertor', it works, when I use the geoConicConformalFrance from https://github.com/rveciana/d3-composite-projections, the legend is drawn and a "blank" canvas.
This is why I know the issue is coming from the the projection and not the other part.

As per understanding, I can set the function diretly or a string that you mapped to the appropriate function. That's why I can't understand the root cause.

**Comment by elvince** [comment]
If you have 5/10 min to update the previous codepen you linked with latest version, this might help to understand why it is not working as expecting?

Or do you need anything from me to understand?
Thanks,

**Comment by sgratzl** [comment]
see https://github.com/sgratzl/chartjs-chart-geo/issues/105 the workaround should work for you for now
