### ISSUE TITLE
Question: Bundling map with the package

### ISSUE THREAD

**Issue by theianjohnson** [sgratzl/chartjs-chart-geo#3]
Hey! Another quick one for you, are we able to use this package without having to make any external API calls? Ala `fetch('https://unpkg.com/world-atlas/countries-50m.json').then((r) => r.json())`

Or is my only solution to manually inline this JSON into my Javascript (in my case into a Vue component)?

**Comment by sgratzl** [comment]
```sh
npm install world-atlas
```

```js
import countries from 'world-atlas/countries-50m.json';
...
```

doesn't work?

**Comment by theianjohnson** [comment]
Sorry I think you're probably right, I think my question is how to get a coropleth map working with Webpack (in my case Vue, because currently nothing is showing up)?

Do I need to
```
import Choropleth from "chartjs-chart-geo";
new Choropleth(ctx, { ... })
```

Or how do I get Vue and the Webpack'd Javascript to recognize the Choropleth map type?

**Comment by sgratzl** [comment]
based on the codepen and vue-chartjs I created: https://codesandbox.io/s/vue-c6skz

**Comment by theianjohnson** [comment]
Aha! I'm not using vue-chartjs, but with your sandboxes I got everything working, thanks so much 👍

**Comment by cocochepeau** [comment]
Hey @sgratzl thanks for your codepen, it's really useful. Do you know why we have blank space at the top and bottom of the generated chart?

**Comment by theianjohnson** [comment]
Also have the same issue as @cocochepeau, I finally just had to add a wrapper element with `overflow: hidden` and some negative top margin or something as a hack

**Comment by cocochepeau** [comment]
Well the thing is I don't see any blank space generated with the Chartjs "native" constructor (see the examples on `README.md`). I imagine it comes from `chartjs-vue`?

**Comment by cocochepeau** [comment]
OK it's already better with `maintainAspectRatio: false` set on the options.

**Comment by sgratzl** [comment]
> OK it's already better with `maintainAspectRatio: false` set on the options.

yeah that would be my first guess to play around with

**Comment by sgratzl** [comment]
the Choropleth plot itself should enforces it aspect ratio already based on the outline

**Comment by anupam42** [comment]
Hello Sir,
How can i import chart-js-geo in angular web app ?

Thanks

**Comment by sgratzl** [comment]
> 
> 
> Hello Sir,
> How can i import chart-js-geo in angular web app ?
> 
> Thanks

what do you mean? and how is this related to this issue?

**Comment by arthurrcarrara** [comment]
I have been trying to set up this Choropleth component, however I'm getting these two errors. 
I have tried to fix it, but I couldn't do it.

Any ideas why is this happening?

TypeError: Cannot read properties of undefined (reading 'plugins')
Error in created hook: "TypeError: Cannot read properties of undefined (reading 'plugins')

Error in mounted hook: "TypeError: chart_js__WEBPACK_IMPORTED_MODULE_0__.default is not a constructor
