### ISSUE TITLE
Map border blurry

### ISSUE THREAD

**Issue by elvince** [sgratzl/chartjs-chart-geo#31]
Hi,

I run the same topojson with the same data with D3 and with your plugin and the only difference I have is on the borders that are blurry.

In the plugin:
![image](https://user-images.githubusercontent.com/7021898/89190143-532b0280-d5a1-11ea-99c6-92472f64c575.png)

With D3:
![image](https://user-images.githubusercontent.com/7021898/89190261-7eaded00-d5a1-11ea-8633-3c010c78fce9.png)

Do you know what can cause this?

I tried the border with option but it is not that. It seems that the "state" border are rendered twice and that may cause it to be blurry.

Thanks,

**Comment by sgratzl** [comment]
have you disabled rendering the outline?

**Comment by elvince** [comment]
ShowOutline on the dataset is set to false, and the outline is "null"

**Comment by elvince** [comment]
Could it be linked to the fitwidth that have harcoded value? 
Could it be linked to the fact that canvas is pixel drawing and svg is vector?

How the states are drawn? Is it one by one or all at once? I mean if chart.js + your plugin draw them individually, this may be the issue that 2 lines will be drawn on top of each other. And as it is piwel related, somethimes, it might not use the same ^^

I'm not enough good with D3/Chart.Js to understand how everything is working, so I just throw ideas !
Thanks!

**Comment by sgratzl** [comment]
> Could it be linked to the fitwidth that have harcoded value?

I cannot see how, it is used to scale the map into the canvas

> Could it be linked to the fact that canvas is pixel drawing and svg is vector?

could be part of it. I don't know which border color you are using

> How the states are drawn? Is it one by one or all at once? I mean if chart.js + your plugin draw them individually, this may be the issue that 2 lines will be drawn on top of each other. And as it is piwel related, somethimes, it might not use the same ^^

I don't get the question, sure each area is drawn by itself they are also individually in the data

may I ask a general question: if you have a D3 version why using chart.js at all for this?

**Comment by elvince** [comment]
Hi,

I'm using in geoFeature:
borderColor: '#000000',
borderWidth: 0.5,

I have the D3 version via datamaps fo angular that is not maintained. While the final rendering is great, there is some drawback that chart.js fix.
I need to have a printable & image download option for my chart. As chat.js is in canvas, it is done by default. For datamaps, I have only the SVG option, so I need to add multiple library in order to get my result.
And I prefer have one library for all my charts than multiple because my team must learn them all instead of one !

For the last question about states drawing order. I was wondering if via Chart.js, the states were drawn one by one and via D3 all at once. But it seems to be a dead end,so we need to find the root cause.

**Comment by sgratzl** [comment]
> borderWidth: 0.5

such as border width is difficult to draw, since you essentially say: draw half a pixel thus creating antialiasing effects

**Comment by elvince** [comment]
sure, but 1px large is too "heavy" compared to the svg result. I can tweak the color to make it less strong visually. but it is not fixing the issue sadly. we are just "hiding it"

For example,, in your cloropeth sample, we have the same blur effect:

![image](https://user-images.githubusercontent.com/7021898/89270336-7f935d00-d63b-11ea-8609-054e99118b24.png)

**Comment by sgratzl** [comment]
can you see a similar effect in other chart.js charts such as line charts?

**Comment by elvince** [comment]
I'm using barchart & pie chart & line chart and I didn't noticed this. But it is not really comparable. Maps contains a lot of drawing that simple chart do not.
With tweaking colors, I managed to get a better result, but not as sharp as svg.

I don't want to waste your time and I really appreciate your help.

Do you know if I can scale up the rendering than "shrink it" to final size?
I mean I would like to see if I render the chart in high resolution and display it in a smaller size, if the result is better;

**Comment by sgratzl** [comment]
> Do you know if I can scale up the rendering than "shrink it" to final size?

take a look at:
https://www.chartjs.org/docs/latest/general/device-pixel-ratio.html

should be worth a try. 

It is in general tough to help you, e.g. the map screenshot from before: I don't know which size the canvas had, whether you zoomed in or not, ... In general sub pixel rendering is highly browser dependent

**Comment by sgratzl** [comment]
closing - stale

**Comment by coisnepe** [comment]
Hey again @sgratzl,
I'm actually facing the same issue, on the map of France too, incidentally.
The file I'm building the map off of seems to have a decent quality indeed:
https://github.com/gregoiredavid/france-geojson/blob/master/departements.geojson
![image](https://user-images.githubusercontent.com/13304454/114708168-529b5c00-9d2b-11eb-86ac-7c881762ccc7.png)

However once I build the map with Chart.js Geo it becomes blurry... I've tried fiddling with `borderWidth` but it doesn't really make a difference
![image](https://user-images.githubusercontent.com/13304454/114708295-7363b180-9d2b-11eb-953b-720404276c62.png)
![image](https://user-images.githubusercontent.com/13304454/114708346-85455480-9d2b-11eb-8702-aa3c3584245d.png)
![image](https://user-images.githubusercontent.com/13304454/114708401-95f5ca80-9d2b-11eb-80dc-09e6ea222dde.png)


The current map with D3 looks like this. I'm switching to Chart.js Geo for ease of use…
![image](https://user-images.githubusercontent.com/13304454/114708489-b0c83f00-9d2b-11eb-8523-983b08fab115.png)

**Comment by sgratzl** [comment]
SVGs and HTML Canvas uses two very different ideas to render things. SVGS are vector graphics which have the inherit benefit that it will look sharp regardless how much you zoom in. HTML Canvas is pixel based, thus the sharpness is determined by the number of available pixels. Zooming in locally on an image won't increase the available pixels. 

You can fiddle with the devicePixelRatio as mentioned which can be used to render, e.g. 2 canvas pixels for each 1 display pixel and let the graphics card figure out how to downscale it.

**Comment by coisnepe** [comment]
Thanks again for your quick reply.
I understand the benefits and drawbacks of svg VS canvas, but my point was that, using the same geojson file, in one library I get a perfectly crisp map while in the other it looks odd even when zoomed out.
My point in the other Issue about documenting the API was that it can be tedious to browse through the individual files, and indeed hard to know where to place the options afterwards -at least as far as I'm concerned. But I know it'd be a lot of work. Perhaps I missed it in the README but just a line or two about how to pass Chart.js options (as opposed to those specific to Charts.js Geo) would be super helpful.
May I add that the link you mentioned that you posted earlier is dead. The updated one, I assume, is this: https://www.chartjs.org/docs/latest/configuration/device-pixel-ratio.html
I assume `devicePixelRatio` has to be passed in `options.devicePixelRatio` ? I tried various values but they all look equally blurry, on a retina Macbook…
