### ISSUE TITLE
The position of color scale

### ISSUE THREAD

**Issue by idoidoido** [sgratzl/chartjs-chart-geo#33]
Hi!

I have made Europe map using outline from World map data.
But, the color scale is right bottom of the map and hidden under several countries.
 I cannot find the way to change the position of color scale or bring the scale to front.
Are there any methods for that?

Thank you.

**Comment by sgratzl** [comment]
take a look at https://github.com/sgratzl/chartjs-chart-geo#legend-and-color-scale or https://codepen.io/sgratzl/pen/GRKLQBw

the legend position can be one of 

```
position: 'left' | 'right' | 'top' | 'bottom' | 'top-left' | 'top-right' | 'top-right' | 'bottom-right';
```

you can also customize whether it is horizontal or vertical

**Comment by idoidoido** [comment]
I have tried the option, but I did not notice that the position is inside colorScale.
Your example is very informative.
Thank you for your quick reply.
