### ISSUE TITLE
Empty map

### ISSUE THREAD

**Issue by phelipetls** [sgratzl/chartjs-chart-geo#36]
Hi, I'm having trouble to get this library to work with a specific API.

[Here is the relevant codepen reproducing the problem](https://codepen.io/phelipetls/pen/KKzegGL).

- Version: 2.1.0.
- Browser: Mozilla Firefox 78.0.2.

I tried to see if it wasn't some small issue but I couldn't find the problem. I tried different projections but still nothing shows up. Also, this particular API does not include a `.transform` property in the response. I plugged some values in it, with no result.

Could this be a bug or am I missing something? Thanks in advance.

**Comment by sgratzl** [comment]
https://codepen.io/sgratzl/pen/NWNzgap?editors=1010 is a version that works for me.

changes: 
 * changes the projection scale
 * add labels to the dataset
 * specify the outline for fitting

**Comment by phelipetls** [comment]
Thank you so much!!
