### ISSUE TITLE
Map rendering as a straight line

### ISSUE THREAD

**Issue by damienderoistecso** [sgratzl/chartjs-chart-geo#38]
Hi

I am trying to create a map of counties of Ireland. I have a topojson file based on x,y coordinates.

When rendering the map, because it is x,y based I used a projection of 'equirectangular'

However, the map renders as a straight line. Maybe some problem with the width???

Here is my code https://codepen.io/damienderoiste/pen/vYGQdrg

If you hover over the line you can see it is picking up the regions and values. 

If you could offer any advice as to why this is happening I'd appreciate it.

Thanks
Damien

**Comment by sgratzl** [comment]
I don't know whether the equirectangular project is the right one, since according to https://github.com/d3/d3-geo#geoEquirectangular it is still based on lat/long and maps the sphere. However, I also don't know which is the right one since I'm not an expert in this field.

**Comment by damienderoistecso** [comment]
According to d3 documentation, 

> "If projection is null, the path uses the identity transformation, where the input 
> geometry is not projected and is instead rendered directly in raw coordinates. This can be 
> useful for fast rendering of already-projected geometry, or for fast rendering of the 
> equirectangular projection."

I think we might not need to use any projection because our topojson already contains raw x and y coordinates. Is it possible to not use any projection in the chart options.

See discussion here https://stackoverflow.com/questions/14646656/drawing-already-projected-geojson-map-in-d3-js

**Comment by sgratzl** [comment]
the library always needs some kind of projection. In the end a projection as used in the library is a way to convert the input data to pixels that fit into the chart.js canvas. So, even if the data are already x/y pixel positions, there is still the matter of scaling to fit into the canvas which the projection needs to do.

**Comment by sgratzl** [comment]
closing since stale
