### ISSUE TITLE
'ChartGeo' is not defined

### ISSUE THREAD

**Issue by indraneel-Actyv** [sgratzl/chartjs-chart-geo#39]
Hello, I am using this Package in my React Project,  I have already used chart.js in my project, but to use Bubble Maps I am using this.

I have downloaded a Topojson File and suppling it to the code locally(using import).

I have also imported chartjs-chart-geo as `import 'chartjs-chart-geo'`

But when i try to run the Project it throws an error ->  'ChartGeo' is not defined.

Can you please help me around this error. 
Thanks in Advance.

**Screenshots / Sketches**
<img width="909" alt="Screenshot 2020-09-23 at 5 06 18 PM" src="https://user-images.githubusercontent.com/59189516/94007449-1ae4bb00-fdbf-11ea-8764-9cf66e09ff3d.png">

**Context**

- Version:
chart.js: "^2.9.3"
chartjs-chart-geo: "^2.1.0"

- Browser: Chrome

**Comment by sgratzl** [comment]
shouldn't it be `import ChartGeo from 'chartjs-chart-geo'` in this setup?, since the global constant is just defined when imported as a script in a website directly

**Comment by indraneel-Actyv** [comment]
I have tried that setup earlier but it results in `Attempted import error: 'chartjs-chart-geo' does not contain a default export (imported as 'ChartGeo').`
<img width="909" alt="Screenshot 2020-09-23 at 9 47 20 PM" src="https://user-images.githubusercontent.com/59189516/94040284-5f378180-fde6-11ea-8f27-c917f5ee437c.png">

**Comment by sgratzl** [comment]
what about `import * as ChartGeo from 'chartjs-chart-geo'`?

**Comment by indraneel-Actyv** [comment]
Yes, it worked thank you !
