### ISSUE TITLE
Choropleth onClick not firing the correct country (sometimes)

### ISSUE THREAD

**Issue by theianjohnson** [sgratzl/chartjs-chart-geo#4]
**Describe the bug**
Choropleth onClick not firing the correct country (sometimes)

**To Reproduce**
1. Go to https://codepen.io/theianjohnson/pen/eYmmZVw?editors=0010
2. Open Chrome's console
3. Hover over Greenland
4. See Russia is highlighted
5. Click on Greenland
6. See Russia is logged in the console

This also happens with Chile and Argentina (they register as New Zealand)

**Expected behavior**
The country that is hovered/clicked on should have the correct `item` in the onClick event handler

(The United States works correctly)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 78

**Comment by sgratzl** [comment]
should be fixed with v1.1.1
