### ISSUE TITLE
FR: Support Natural Earth TopoJSON files

### ISSUE THREAD

**Issue by Offbeatmammal** [sgratzl/chartjs-chart-geo#40]
Would it be possible to support the use of Natural Earth TopoJSON files for Country/State level so we have a consistent way to work with the "world"
eg drive from
https://github.com/mtraynham/natural-earth-topo/blob/master/topojson/ne_10m_admin_1_states_provinces.json and allow filtering/outline at a specific country or continent level?

**User story**
my specific use-case has been trying to get this working with Australian States

**Additional context**
having a consistent, global, solution would make this a much more useful package... I love the US capabilities and (tested) data, but struggling to get it working consistently for non-US target

**Comment by sgratzl** [comment]
you can set the projection method used see https://github.com/sgratzl/chartjs-chart-geo#scales. I don't fully get what the issue is

**Comment by Offbeatmammal** [comment]
sorry, probably explained it poorly.
Currently the samples work either for US/States or the Germany specific, and rely on a variety of (untested) TopoJSON sources for other regions... the Natural Earth source seems to offer fairly complete datasets (though maybe they could be a little more current) but I'm struggling to actually get them working

am I missing a really obvious way to take a source of
`
     fetch('https://raw.githubusercontent.com/mtraynham/natural-earth-topo/master/topojson/ne_50m_admin_1_states_provinces.json')
        .then((r) => r.json())
        .then((data) => { ... `
and filter it down so I'm only looking as States/Provinces for (say) Australia?

**Comment by sgratzl** [comment]
I still don't fully understand the problem. 

I quickly created https://codepen.io/sgratzl/pen/pobzjKE?editors=1010 and had no problem with the library

**Comment by Offbeatmammal** [comment]
d'oh, looking at my code again this morning and comparing to your example... I'd got the filtering wrong
thanks for your patience (and the sample that got me back on track!)
