### ISSUE TITLE
Zoom plugin supported

### ISSUE THREAD

**Issue by damienderoistecso** [sgratzl/chartjs-chart-geo#41]
Is it possible to use the following plugin with this library

https://github.com/chartjs/chartjs-plugin-zoom

I managed to create a map but when I try and use the plugin to add zoom to my map, it doesn't work

See codepen here https://codepen.io/damienderoiste/pen/ZEOzjKO

**Comment by sgratzl** [comment]
see also https://github.com/sgratzl/chartjs-chart-geo/issues/28

this plugin is mainly designed for a static image. If you want free scaling, I would suggest using a more sophisticated library like mapbox.

**Comment by damienderoistecso** [comment]
Thanks for the reply. This library is great for simple choropleth maps and is very lightweight and easy to use when you just want to render data on a map. If the zoom could be incorporated I think it would be a great feature. Mapbox is a bit heavy for my purpose but thanks for the suggestion.

**Comment by damienderoistecso** [comment]
Hi, just wondering if you have update on whether this feature might be included in any future release?

Thanks

**Comment by sgratzl** [comment]
I don't have the free capacity right now to take a closer look at this, since to get this one in the speed I want to is a tricky one.

**Comment by damienderoistecso** [comment]
> I don't have the free capacity right now to take a closer look at this, since to get this one in the speed I want to is a tricky one.

Thanks for the update and I appreciate the complexity of the enhancement. 

I work in the Central Statistics Office Ireland (Ireland's official national statistical office) and we use this library in our new open data platform https://data.cso.ie/ to plot official statistical data on maps. The zoom is the last feature we need to roll this out on a large scale across many of our datasets. See attached screenshot of the how the map feature will look like once implemented.

![image](https://user-images.githubusercontent.com/53211688/109125145-a0401300-7743-11eb-9705-bfccfe09c0de.png)

**Comment by sgratzl** [comment]
that looks great. seems like a very complex topojson file. I get why you are looking for a zooming feature on that. 

Again for such a complex setup I would usually suggest my clients an advanced map library such as Leaflet or MapBox, since rendering is getting more expensive and a raster/tiling approach is more appropriate.

**Comment by sgratzl** [comment]
wontfix. the projection logic is not a standard chart.js scale with the zoom plugin is using. Thus, making it compatible would take a lot of time and also then be performant is another complex thing

**Comment by syorito-hatsuki** [comment]
Sad :(
