### ISSUE TITLE
Color transition

### ISSUE THREAD

**Issue by idoidoido** [sgratzl/chartjs-chart-geo#42]
Hi,

I am using your script very conveniently.
I present time course using this map.
In graphs created by chart.js, value update changes its color gradually.
Is it possible such color transition in this script?

Masashi Idogawa

**Comment by sgratzl** [comment]
for performance reason in chart.js 2.9 animations are disabled. With the upcoming version 3 for chart.js 3 animations will be enabled again and animations should work as expected, e.g.: https://codepen.io/sgratzl/pen/GRqdYjo?editors=1010

**Comment by idoidoido** [comment]
Thank you for your reply.
I must use chart.js v2.9 for the time being to preserve compatibility between several scripts.
Is it impossible to enable the function in v2.9?

**Comment by sgratzl** [comment]
you can change the default configuration of disabling the animations by:

```
delete Chart.defaults.choropleth.animation;
```

see also: https://codepen.io/sgratzl/pen/yLJEXOG?editors=1010

**Comment by idoidoido** [comment]
In my scripts for v2.9, this seems to work well.
The performance has no problem until now.

Thank you very much!
