### ISSUE TITLE
Setting the graticule/ outline colour moves it in front of the colour scale

### ISSUE THREAD

**Issue by d9nny** [sgratzl/chartjs-chart-geo#44]
Great plugin thanks.

Assuming I'm setting it correctly, I'm having a small issue when setting the `outlineBorderColor` and `graticuleBorderColor`. It's causing the colour scale to sit behind them, making it hard to read.

**To Reproduce**
```
this.chart = new window['Chart'](context, {
            type: 'choropleth',
            data: {
                labels: this.labels,
                datasets: {
                   label: 'Countries',
                   data: Countries.map((d) => ({
                     feature: d,
                     value: this.data[d.properties.name],
                   })),
                   outlineBorderColor: this.theme === 'light' ? LightThemeColor2 : DarkThemeColor2,
                   graticuleBorderColor: this.theme === 'light' ? LightThemeColor2 : DarkThemeColor2,
                },
            },
            options: this.options,
        });
   ```     

**Expected behavior**

For the `graticule` & `outline` to sit behind the colour scale.

**Screenshot**

<img width="191" alt="Screenshot 2020-12-18 at 15 26 15" src="https://user-images.githubusercontent.com/14181629/102631283-6e0fa500-4145-11eb-9b2c-8c53a12eed50.png">

**Context**

- Version: "^2.1.0"
- Browser: Chrome

**Comment by sgratzl** [comment]
fixed in the next beta release, see referenced commit: https://github.com/sgratzl/chartjs-chart-geo/commit/49d142ff144e9d76eb059c6c7c1b1d516befc362
