### ISSUE TITLE
How to find the source in JS ?

### ISSUE THREAD

**Issue by NeilBeyne** [sgratzl/chartjs-chart-geo#46]
Hi,
I do not find how to get the final version of Chart.Geo.min.js and Chart.Geo.js here, or anywhere... 
I would like to use the beta version, but I find nowhere the way to download these files.
All files in zip that we get here, do not get this compile file ended.

Thanks for your answer,
Regards

**Comment by sgratzl** [comment]
starting with v3 (which is compatible with chart.js 3) the repository structure and filenames have changed. The [release page](https://github.com/sgratzl/chartjs-chart-geo/releases) contains the latest (pre-) release including a `package.tgz` which itself contains a build directory with the compiled files. However, I would encourage in using the NPM package directory or a CDN service like unpkg or jsdelivr to use this chart.js plugin

**Comment by NeilBeyne** [comment]
Thanks !
