### ISSUE TITLE
Do D3 Projection functions (like center) work with this?

### ISSUE THREAD

**Issue by joecons97** [sgratzl/chartjs-chart-geo#48]
Hi!

I've started using ChartJs Geo recently because I need to render a map of the earth to represent some data but the map is being cut off at the top. To fix this, I wanted to the D3 Projection function "projection.center" but when I call it, absolutely nothing seems to be happening.

I've done some testing and I've also found that scale, translate and a few others don't work either (but clipAngle and rotation do work).

Could you help me figure out how to offset my map on the y axis please?

The code I'm using to try and offset the map is as follows
`d3.geoPatterson().center([0,-50])`

I've also tried many other projections with the exact same result.

**Comment by sgratzl** [comment]
can you create a codepen/codesandbox illustrating your issue, please?

**Comment by joecons97** [comment]
> can you create a codepen/codesandbox illustrating your issue, please?

Here you go: https://codepen.io/joecons97/pen/yLaEezj

Check line 21 for the "center" call

**Comment by sgratzl** [comment]
a feature of this plugin is that it automatically scales the map to be within the canvas. It takes the projection and scales/translates it such that the outline/map will fit onto the canvas. This explains why a shift didn't do anything cause it was inverted by the automatic fitting. 

I'm not fully sure yet why it is not fitting correctly. However, when I disable the legend:

```
,
      plugins: {
        legend: {
          display: false
        }
      }
```

noet the new notation in the latest chart.js beta version

it looks like: 

![image](https://user-images.githubusercontent.com/4129778/103790608-6d18b780-500f-11eb-8129-ccf29d9d6b25.png)

**Comment by sgratzl** [comment]
disabling the (useless) legend for now should fix it for you, I just pushed a fix that will fix it in case the legend is enabled.

**Comment by joecons97** [comment]
Okay brilliant, thank you very much!
