### ISSUE TITLE
Map wihtout Antartica ! Great ! =) but with a big withespace at the bottom of the map =(

### ISSUE THREAD

**Issue by NeilBeyne** [sgratzl/chartjs-chart-geo#49]
Hi,

Is there a way to remove / trim the map at the bottom when we remove Antartica ?

Here a sample :
https://codepen.io/Neil-Beyne/pen/eYdQYwp

Thanks !

PS : I love this plugin !!! it's just great !!!! well done for all of this !!!

**Comment by sgratzl** [comment]
take a look at https://codepen.io/sgratzl/pen/BaLGywe?editors=0010

you have to specify the outline, otherwise the world = with Antarctica will be used.

**Comment by NeilBeyne** [comment]
You're the one !
You always have the solution !
It works great !!!!

**Comment by NeilBeyne** [comment]
I also put a ratio to 1.5. Like this I get less whitespace. Just great ! 
I did not know that we could use [...countries], which it's greatest than great !!! =)

**Comment by TautvydasDerzinskas** [comment]
I am getting the same issue and it looks like your example: https://codepen.io/sgratzl/pen/BaLGywe?editors=0010 is not valid anymore
