### ISSUE TITLE
Buble map cuts off bubbles at edge

### ISSUE THREAD

**Issue by fvhockney** [sgratzl/chartjs-chart-geo#5]
**Describe the bug**
When using bubbleMap and a bubble appears on a point close to the edge, the bubble is cut off

**Expected behavior**
I would expect that one of two things happen:

1. The map would resize so that the bubble is not cut off (less ideal)
2. the bubble would extend outside of the canvas (probably not possible)

**Screenshots**
![image](https://user-images.githubusercontent.com/30329026/70237907-6bbff000-1768-11ea-886e-ea2bfc6ef9d8.png)

**Comment by sgratzl** [comment]
I think resizing the map is the way to go. As in that you define a margin around that map. It won't be depending on the bubble size but one can tune that manually such that it fits good enough. Making it depending on the bubble size would mean that the size of the map would change if you change the data which is not ideal.

**Comment by fvhockney** [comment]
hmm. I went through several iterations of attempting the margins trick before posting. While it does work, it is far from ideal since the containing box may be quite large affecting placement of elements around it. As I see it the ideal solution would be for the bubble to have some sort of index which causes it to overflow the canvas without affecting the position of surrounding elements or the chart size. However, I doubt this is possible. If not, feel free to close the issue and I'll muddle along with the margin trick.

**Comment by sgratzl** [comment]
you could also ask the chart.js guys about advice since in the end it is just a bubble chart and in a regular bubble chart you can encounter the same problem

**Comment by fvhockney** [comment]
oh really, had no idea one had the same problem in a regular bubble chart. I will go bug them then :-)

**Comment by fvhockney** [comment]
So they apparently fixed this issue with https://github.com/chartjs/Chart.js/pull/3476, which I had tried ... it does manage to give me the padding I need, but cuts off some of the map, I suspect because the map doesn't recalculate the bounding box?
```
...
padding: 10,
...
```
![image](https://user-images.githubusercontent.com/30329026/70241482-64e8ab80-176f-11ea-9ce8-cd5960a1cdeb.png)

**Comment by sgratzl** [comment]
version 1.1.2 disables the clipping for the bubble map points. Thus, as in https://github.com/sgratzl/chartjs-chart-geo/blob/master/samples/bubbleMap.html when you apply the padding the map shrinks accordingly but the bubbles won't get clipped at the padding border
