### ISSUE TITLE
Remove the value portion that shows the color number within the label

### ISSUE THREAD

**Issue by dawad725** [sgratzl/chartjs-chart-geo#51]
![Screen Shot 2021-02-12 at 12 07 51 PM](https://user-images.githubusercontent.com/55368135/107799051-f025df80-6d2a-11eb-80b1-6551884ae254.png)

Is there a way to remove the value attribute from the label that you see when you hover over a country? I still want to use it to color the map, but I hate that it's still in the label. Any help you can offer would be amazing! 

Thanks, 
Dave

**Comment by sgratzl** [comment]
this is standard chart.js tooltip. So, you can take a look at their docs how to get rid of the color. I assume it is overriding some of the tooltip callbacks

**Comment by dawad725** [comment]
In case anyone is looking for the same thing. This is how I resolved it. 

```
      options: {
        tooltips: {
          callbacks: {
            label: function (tooltipItem, data) {
              let label = data.labels[tooltipItem.index];
              return label
            }
          }
        },
```
