### ISSUE TITLE
Datalabels plugin not working with latest version

### ISSUE THREAD

**Issue by mateodif** [sgratzl/chartjs-chart-geo#53]
When I include the latest datalabels plugin available for ChartJS v3.0 or later, which I had to do manually (see https://github.com/chartjs/chartjs-plugin-datalabels/discussions/213) it doesn't seem to be doing anything. No labels load, no errors log, etc.

**To Reproduce**

1. Build latest chartjs-plugin-datalabels from chartjs-next branch.
2. Include the plugin in browser tag next to chartjs and this plugin.
3. Include a minimal configuration in the options of the chart.
4. Run the result.

**Expected behavior**

Datalabels working so we can display things like state names in the map.

Cheers.

**Comment by sgratzl** [comment]
take a look at https://codepen.io/sgratzl/pen/VwPXPEq?editors=0010
![image](https://user-images.githubusercontent.com/4129778/114557690-ea1f8280-9c37-11eb-9a32-7a6fc10b0dab.png)
