### ISSUE TITLE
Color interpolate function not working in v3.0.0-rc.0

### ISSUE THREAD

**Issue by m-radzikowski** [sgratzl/chartjs-chart-geo#56]
The `scales.color.interpolate` property that can take either a function `(number => string)` or string interpolation name works correctly with string names, but when providing a function, it fallbacks to default "blues".

**To Reproduce**

Create choropleth chart with options:

```
{
        scales: {
            color: {
                interpolate: n => n === 0 ? '#000' : '#f00',
            }
        },
}
```

**Expected behavior**

Should show a map with black and red regions. Instead, it uses default "blues" scale, like the `interpolate` option would not be provided at all.

Moreover, when providing a function created with [color-interpolate](https://www.npmjs.com/package/color-interpolate) I get an error "Cannot read property 'map' of undefined" which makes me suspect that the number is not passed to the interpolate function at all.

**Context**

- Version: 3.0.0-rc.0
- Browser: Chrome 89.0.4389.90

**Comment by sgratzl** [comment]
chart.js supports advanced configuration. Thus, if you provide a function, it will think that you wanna customize the option based on the given context. 

The solution is to wrap the function in another function:

```js
{
        scales: {
            color: {
                interpolate: () => (n => n === 0 ? '#000' : '#f00'),
            }
        },
}
```

**Comment by m-radzikowski** [comment]
Oh right, that works, thanks!

But the TS typings are incorrect then:

```
TS2322: Type '() => (n: any) => string' is not assignable to type '((normalizedValue: number) => string) | "blues" | "brBG" | "buGn" | "buPu" | "cividis" | "cool" | "cubehelixDefault" | "gnBu" | "greens" | "greys" | "inferno" | "magma" | "orRd" | ... 25 more ... | undefined'.   
Type '() => (n: any) => string' is not assignable to type '(normalizedValue: number) => string'.     
Type '(n: any) => string' is not assignable to type 'string'.
```

**Comment by sgratzl** [comment]
I found a way to disable the `scriptable` option for this option. Thus, soon you can use the regular function as before

**Comment by laventnc** [comment]
incase anyone stumbles here wondering why the interpolate function isn't working with a logarithmic color scale... you need to register the base ColorScale as well.
