### ISSUE TITLE
Custom color pallete for highlighting the countries in the choropleth instead of interpolate

### ISSUE THREAD

**Issue by SteffiKeranJ** [sgratzl/chartjs-chart-geo#57]
It would be great if we can specify custom colors in the `colorScale`
I am trying to highlight just 5 countries in the geoMap. Right now, am using:
```
geo: {
        colorScale: {
            display: true,
            interpolate: 'blues',
            missing: 'white',
            legend: {
                display: 'true',
                position: 'bottom-right'
            }
        }
    }
```
What I wanted is to specify my own colors for highlighting the 5 countries in the geo Map. I would be great to have that feature

**Comment by sgratzl** [comment]
you can provide a custom function which maps a normalized value to a color, e.g.

```js
{
  interpolate: (value) => value < 0.5 ? 'red' : 'blue'
}

**Comment by SteffiKeranJ** [comment]
Is there a way I can strictly assign the highlight color irrespective of the values?
For example, I want to highlight the top 5 wealthy countries. The first country should be green. The second one -blue, 3rd - yellow, 4th- red and 5th-pink. I am looking for something like this.

**Comment by sgratzl** [comment]
why not encode this hierarchy as the value that is used within the choropleth map: 

e.g. 
```
0 ... non-important
0.6 ... 5nd most
0.7 ... 4nd most
0.8 ... 3nd most
0.9 ... 2nd most
1 ... most whealthy
```
and a custom colormap function like:
```
(v) => {
  if (v === 0) return 'white';
  if (v === 1) return 'red';
  ...
```

**Comment by sgratzl** [comment]
as an alternative, you can customize the `backgroundColor` function in which you will have access to the raw county object. 

https://github.com/sgratzl/chartjs-chart-geo/blob/b46dd32b5f1d8333ab0f2a8fff0eb29a8456a48e/src/controllers/ChoroplethController.ts#L127-L133

**Comment by SteffiKeranJ** [comment]
This should work, Thank you !
