### ISSUE TITLE
geo colorScale display false does not seem to work in https://unpkg.com/chart.js@next

### ISSUE THREAD

**Issue by vavdb** [sgratzl/chartjs-chart-geo#58]
geo: {
        colorScale: {
          display: false,
        },
      },     

Codepen with @next where this is broken:
https://codepen.io/vavdb/pen/jOybeQY
https://unpkg.com/chart.js@next
https://unpkg.com/chartjs-chart-geo@next

Codepen with not @next where this works
https://codepen.io/vavdb/pen/XWpmxoy
https://unpkg.com/chart.js
https://unpkg.com/chartjs-chart-geo

**Comment by sgratzl** [comment]
they are now regular scales. Thus, you can use: 

```js
options: {
  scales: {
    color: {
      display: false,
    }
 }
}
```

**Comment by vavdb** [comment]
That works, thanks!
