### ISSUE TITLE
Boundary color for the countries in the choropleth

### ISSUE THREAD

**Issue by SteffiKeranJ** [sgratzl/chartjs-chart-geo#60]
I have created a choropleth map of projection 'naturalEarth1'. I wanted to change the boundary colors of the country. I wanted to customize the boundary width also, say, 0.2px. How do I do it in chartjs-chart-geo ?

**Comment by sgratzl** [comment]
you can customize the `borderColor` and `borderWidth`. However, how does one render 0.2px in a pixel based canvas?

**Comment by SteffiKeranJ** [comment]
Not necessary to be 0.2px. I was looking for a way to control the thickness of the boundaries of the countries in the choropleth

**Comment by sgratzl** [comment]
e.g. https://codepen.io/sgratzl/pen/qBRRZYq?editors=0010

**Comment by SteffiKeranJ** [comment]
Thank you @sgratzl ! This is perfect!
