### ISSUE TITLE
How can the colorscale be hidden ?

### ISSUE THREAD

**Issue by coisnepe** [sgratzl/chartjs-chart-geo#61]
Hey @sgratzl , thanks for the work you put into this library !

I've been struggling to find a way to hide the colorscale, and haven't been able to achieve it so far. `options.plugins.legend.display` deals with the actual legend, not the colorscale... I'd be super grateful if someone could point me in the right direction!

![image](https://user-images.githubusercontent.com/13304454/114589308-d69c0800-9c87-11eb-8294-3a48fd777c1a.png)

I was also wondering whether there was documentation about the API, such as all the options that can be passed to the Chart object that are specific to Chart.js Geo - if there are any indeed?

**Comment by sgratzl** [comment]
re hiding scale:
 see also https://github.com/sgratzl/chartjs-chart-geo/blob/17132af15391fe3e7f2454ac49d8743b5a25abdc/samples/albersLegend.html#L44-L49, you can configure the color scale similar to other ones, e.g. by setting

```js
 color: {
   display: false
 }
```

should hide it

re api:

The code is fully written in TypeScript. Thus, you can find all the available options as part of the interfaces describing the controller or element:

 such as https://github.com/sgratzl/chartjs-chart-geo/blob/17132af15391fe3e7f2454ac49d8743b5a25abdc/src/controllers/GeoController.ts#L221-L250
 https://github.com/sgratzl/chartjs-chart-geo/blob/17132af15391fe3e7f2454ac49d8743b5a25abdc/src/elements/GeoFeature.ts#L5-L32

**Comment by coisnepe** [comment]
Awesome! I wish all maintainers replied as quickly and thoroughly as you just did. Thanks!
