### ISSUE TITLE
Set Projection scale 

### ISSUE THREAD

**Issue by xblack0** [sgratzl/chartjs-chart-geo#62]
![image](https://user-images.githubusercontent.com/5411026/114625000-a7ef5300-9cc2-11eb-9243-3341cf6117e8.png)

how to zoom in or change the projection, I cannot figure it out.

**Comment by sgratzl** [comment]
I guess you need to set a proper `outline`:

https://github.com/sgratzl/chartjs-chart-geo/blob/17132af15391fe3e7f2454ac49d8743b5a25abdc/src/controllers/GeoController.ts#L222-L227

**Comment by xblack0** [comment]
it work thanks alot 

![image](https://user-images.githubusercontent.com/5411026/114655588-88295080-9cfd-11eb-9fbc-7cb5e4443847.png)
