### ISSUE TITLE
Legend Ticks

### ISSUE THREAD

**Issue by kazoompa** [sgratzl/chartjs-chart-geo#63]
Hi,

I am trying to modify the value of the legend's ticks and came across an older issue with the following solution:

```
{
  colorScale: {
    ticks: {
      callback: (v) => v.toLocaleString()
    },
  }
}
```

However, when I try your [example](https://codepen.io/sgratzl/pen/PoNdrXY) I do not see any changes, I believe the callback is not called.

 I am using:

- Version: 2.1.0
- Browser: Chrome

Many thanks,

**Comment by sgratzl** [comment]
>     * Version: 2.1.0

The current version of chart.js and is this plugin is 3.0. The codepen is referring to the chart.js v3 version. However, chart.js 3 includes several breaking changes, including the tooltip handling. Take a look at the chart.js documentation

**Comment by kazoompa** [comment]
Thanks Samuel, I read the docs and also took a look at your code and the `IColorScaleOptions` but I could not find how to manipulate the ticks, especially via a callback.

I tried the following options to see if I could change the ColorScale ticks:

```
        geo: {
          colorScale: {
            ticks: {
              min:0,
              max:1
            },
            display: true,
            position: 'bottom'
          },
        }
```
The `ticks` had no effect, my reference was this [issue](https://github.com/sgratzl/chartjs-chart-geo/issues/21). 

The actual issue is that when my dataset has only 1 value the ticks go from [0, 0.5, 1.0, 1.5, 2.0] which in my case has no sense.

I would have a upgraded to the latest version but cannot do this at this point. If you had the time, I would appreciate any hints.

Best,

**Comment by sgratzl** [comment]
can you create a codepn illustrating your issue. The example one from before was with chart.js 3

**Comment by sgratzl** [comment]
stale, closing

**Comment by shubhayu222** [comment]
Facing this problem when I applied the equirectangular projection. I wanted ticks as integer but getting as float.
        `scales: { projection: { axis: 'x', projection: 'equirectangular',  }, ColorScale: { axis: 'x', ticks: { precision: 0 }, } }`

**Comment by sgratzl** [comment]
the scale name should be `color: ...` can you try that

**Comment by shubhayu222** [comment]
Is there anything to try. Issue is still not resolved. Tried using chart.js v4.2.1 and v4.4.0.

**Comment by sgratzl** [comment]
```
    scales: {
      projection: {
        axis: 'x',
        projection: 'albersUsa',
      },
      size: {
        axis: 'x',
        size: [1, 20],
        ticks: {
          callback: (v) => {
            return `x${v}`;
          },
        },
      },
    },
```

shows
![image](https://github.com/sgratzl/chartjs-chart-geo/assets/4129778/67ca9f15-a154-4fe5-9938-2f043cb90283)

for me

**Comment by shubhayu222** [comment]
`        scales: {
          projection: {
            axis: 'x',
            projection: this.projectionValue, 
          },
          size: {
            axis: 'x',
            ticks: {
              callback: (v) => {
                return Number.isInteger(v) ? v : null;
              },
            },
          },
        }`
For angular I make it work like this in Angular. Thanks for your reference. (size: [1, 20] is not working in typescript)

Great library <3
