### ISSUE TITLE
Which loader do I need?

### ISSUE THREAD

**Issue by bnisevic** [sgratzl/chartjs-chart-geo#64]
I'm getting:

```
WebpackError at /search/
            ModuleParseError in 
            Module parse failed: Unexpected token (6093:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 	        }
| 	        if (this.showOutline()) {
> 	            this.getMeta().dataset?.draw(chart.ctx);
| 	        }
| 	        if (clipMap === true || clipMap === 'graticule' || clipMap === 'outline+graticule') {
```

**Context**
I am running webpack 4.44.2 with: 
```
    "babel-cli": "^6.5.0",
    "babel-core": "^6.5.0",
    "babel-loader": "^7.1.5",
    "babel-plugin-transform-runtime": "^6.5.0",
    "babel-polyfill": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-preset-stage-2": "^6.5.0",
    "babel-runtime": "^6.5.0",
```
I figure that babel is outdated. But it's a legacy app and I had trouble upgrading babel to 7 and babel-loader 8. So, I reverted those. Is it possible to fix this error without upgrading babel and the loader?

Also, it would be helpful if it's possible to throw an example how to integrate this plugin in webpack? I couldn't find that in the examples in this repo.

Thanks!

**Comment by sgratzl** [comment]
please try out version 3.0.1

**Comment by hwoodiwiss** [comment]
I installed about 5 minutes before this update. Works a charm in an angular project now, thank you.

**Comment by bnisevic** [comment]
Thanks. Upgrading helped with loader error. But it would be really helpful to have some integration examples. I can not import ChartGeo from chartjs-chart-geo. It is not there. So, how this plugin can be used integrated with chart.js in JS apps and without using script tag in head?

**Comment by bnisevic** [comment]
The only reference of "ChartGeo" in chartjs-chart-geo code I can find is in package.json under key "global". But I can't find anything about this key in the package.json reference https://docs.npmjs.com/cli/v7/configuring-npm/package-json

**Comment by bnisevic** [comment]
My problem is that however I import chartjs-chart-geo I get `Uncaught (in promise) TypeError: ChartGeo is undefined`.

**Comment by hwoodiwiss** [comment]
From my usage, if you're using ES modules, you don't need ChartGeo, you want to import a level down.

This is what I have in the Angular component I'm building, and this works.

```ts
import { Chart } from "chart.js";
import { topojson } from "chartjs-chart-geo";
```

Hope this helps.

**Comment by bnisevic** [comment]
@hwoodiwiss thanks for being helpful! How do you register choropleth and bubblemap types? Should I do something like here:
https://github.com/sgratzl/chartjs-chart-geo/blob/v3.0.0/src/index.umd.ts

**Comment by hwoodiwiss** [comment]
So, oddly I haven't needed to do anything extra to register the Choropleth (haven't tried with the bubble map) in this component.

My best guess is that this line:
```ts
Chart.register(...registerables);
```
Just after my includes in another component is doing the job.

**Comment by bnisevic** [comment]
Thanks @hwoodiwiss! You helped me a lot!
