### ISSUE TITLE
Integrating with vue-chartjs

### ISSUE THREAD

**Issue by nikolaBrkusanin** [sgratzl/chartjs-chart-geo#65]
How can I use chart geo with vue-chartjs? These are components that I'm using

```html
<script>
import { generateChart, mixins } from "vue-chartjs";
// import to auto register
import "chartjs-chart-geo";

const Choropleth = generateChart("choropleth", "choropleth");

export default {
  extends: Choropleth,
  mixins: [mixins.reactiveProp],
  props: ["options"],
  mounted() {
    this.renderChart(this.chartData, this.options);
  }
};
</script>
```

```vue
<template>
  <div id="app">
    <choropleth-chart :chart-data="chartData" :options="options"/>
  </div>
</template>

<script>
import ChoroplethChart from "../charts/MapChart.vue";
import { topojson } from "chartjs-chart-geo";
import countriesTopoJson from "world-atlas/countries-50m.json";

const countries = topojson.feature(
  countriesTopoJson,
  countriesTopoJson.objects.countries
).features;

export default {
  name: "App",
  components: {
    ChoroplethChart
  },
  data() {
    return {
      chartData: {
        labels: countries.map(d => d.properties.name),
        datasets: [
          {
            label: "Countries",
            backgroundColor: context => {
              if (context.dataIndex == null) {
                return null;
              }
              const value = context.dataset.data[context.dataIndex];
              return `rgb(0, 0, ${value.value * 255})`;
            },
            data: countries.map(d => ({ feature: d, value: Math.random() }))
          }
        ]
      },
      options: {
        showOutline: true,
        showGraticule: false,
        legend: {
          display: false
        },
        scale: {
          projection: "equirectangular"
        }
      }
    };
  }
};
</script>


```

, but I'm getting this error
```
`ERROR in ./node_modules/chartjs-chart-geo/build/index.umd.js
Module not found: Error: Can't resolve 'chart.js/helpers' in 'C:\xampp\htdocs\cbh\node_modules\chartjs-chart-geo\build'
 @ ./node_modules/chartjs-chart-geo/build/index.umd.js 9:102-129
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./modules/Reporting/Resources/assets/js/components/charts/MapChart.vue?vue&type=script&lang=js&
 @ ./modules/Reporting/Resources/assets/js/components/charts/MapChart.vue?vue&type=script&lang=js&
 @ ./modules/Reporting/Resources/assets/js/components/charts/MapChart.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./modules/Reporting/Resources/assets/js/components/dashboard/DashboardBarStackedChart.vue?vue&type=script&lang=js&
 @ ./modules/Reporting/Resources/assets/js/components/dashboard/DashboardBarStackedChart.vue?vue&type=script&lang=js&
 @ ./modules/Reporting/Resources/assets/js/components/dashboard/DashboardBarStackedChart.vue
 @ ./modules/Reporting/Resources/assets/js/app.js
 @ multi ./modules/Reporting/Resources/assets/js/app.js`
```

![image](https://user-images.githubusercontent.com/80686116/115718284-417dcb00-a37b-11eb-83ad-0c4f584cb8f5.png)
![image](https://user-images.githubusercontent.com/80686116/115718324-4d698d00-a37b-11eb-95e3-66301c2367ec.png)

Thanks

**Comment by AliakseiMatsuk** [comment]
Hi @nikolaBrkusanin !
It seems to me that you are using incompatible versions of the libraries

v2.X.X only works with Chart.js >= 2.8.0 < 3.0.0
v3.X.X only works with Chart.js >= 3.0.0

In your case, you should use version 2.1.0

**Comment by adry7ana** [comment]
i have the same problem, but in react. This is my versión of React: "react": "^16.10.2",
and this is my version of chartjs and chart-geo:
"chart.js": "^2.9.3",
"chartjs-chart-geo": "^3.1.0",

**Comment by sgratzl** [comment]
chartjs-chart-geo version 3 only works with chart.js version 3

**Comment by crudobaker** [comment]
> How can I use chart geo with vue-chartjs? These are components that I'm using
> 
> ```
> <script>
> import { generateChart, mixins } from "vue-chartjs";
> // import to auto register
> import "chartjs-chart-geo";
> 
> const Choropleth = generateChart("choropleth", "choropleth");
> 
> export default {
>   extends: Choropleth,
>   mixins: [mixins.reactiveProp],
>   props: ["options"],
>   mounted() {
>     this.renderChart(this.chartData, this.options);
>   }
> };
> </script>
> ```
> 
> ```
> <template>
>   <div id="app">
>     <choropleth-chart :chart-data="chartData" :options="options"/>
>   </div>
> </template>
> 
> <script>
> import ChoroplethChart from "../charts/MapChart.vue";
> import { topojson } from "chartjs-chart-geo";
> import countriesTopoJson from "world-atlas/countries-50m.json";
> 
> const countries = topojson.feature(
>   countriesTopoJson,
>   countriesTopoJson.objects.countries
> ).features;
> 
> export default {
>   name: "App",
>   components: {
>     ChoroplethChart
>   },
>   data() {
>     return {
>       chartData: {
>         labels: countries.map(d => d.properties.name),
>         datasets: [
>           {
>             label: "Countries",
>             backgroundColor: context => {
>               if (context.dataIndex == null) {
>                 return null;
>               }
>               const value = context.dataset.data[context.dataIndex];
>               return `rgb(0, 0, ${value.value * 255})`;
>             },
>             data: countries.map(d => ({ feature: d, value: Math.random() }))
>           }
>         ]
>       },
>       options: {
>         showOutline: true,
>         showGraticule: false,
>         legend: {
>           display: false
>         },
>         scale: {
>           projection: "equirectangular"
>         }
>       }
>     };
>   }
> };
> </script>
> ```
> 
> , but I'm getting this error
> 
> ```
> `ERROR in ./node_modules/chartjs-chart-geo/build/index.umd.js
> Module not found: Error: Can't resolve 'chart.js/helpers' in 'C:\xampp\htdocs\cbh\node_modules\chartjs-chart-geo\build'
>  @ ./node_modules/chartjs-chart-geo/build/index.umd.js 9:102-129
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./modules/Reporting/Resources/assets/js/components/charts/MapChart.vue?vue&type=script&lang=js&
>  @ ./modules/Reporting/Resources/assets/js/components/charts/MapChart.vue?vue&type=script&lang=js&
>  @ ./modules/Reporting/Resources/assets/js/components/charts/MapChart.vue
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./modules/Reporting/Resources/assets/js/components/dashboard/DashboardBarStackedChart.vue?vue&type=script&lang=js&
>  @ ./modules/Reporting/Resources/assets/js/components/dashboard/DashboardBarStackedChart.vue?vue&type=script&lang=js&
>  @ ./modules/Reporting/Resources/assets/js/components/dashboard/DashboardBarStackedChart.vue
>  @ ./modules/Reporting/Resources/assets/js/app.js
>  @ multi ./modules/Reporting/Resources/assets/js/app.js`
> ```
> 
> ![image](https://user-images.githubusercontent.com/80686116/115718284-417dcb00-a37b-11eb-83ad-0c4f584cb8f5.png) ![image](https://user-images.githubusercontent.com/80686116/115718324-4d698d00-a37b-11eb-95e3-66301c2367ec.png)
> 
> Thanks

Hey @nikolaBrkusanin ?
Did you have success with that integration?
Thanks!

**Comment by crudobaker** [comment]
Hey Team! Just in case @nikolaBrkusanin still needs another way to use `chartjs-chart-geo` with `vue`.
I share you the way I integrated both, `vue-charts-3` and `chartjs-chart-geo`.

`MyChoroplethChart.ts`
```
import { defineChartComponent } from 'vue-chart-3'
import { Chart } from 'chart.js'
import { ChoroplethController, GeoFeature, ColorScale, ProjectionScale } from 'chartjs-chart-geo'

Chart.register(ChoroplethController, GeoFeature, ColorScale, ProjectionScale)

export const MyChoroplethChart = defineChartComponent('choropleth-chart', 'choropleth')
```

`MyPage.vue`
```
<script setup>
  const data = {...}
  const options = {...}
</script>
<template>
  <SChoroplethChart :chartData="data" :options="options" />
</template>
```

**Comment by jackstruck** [comment]
An update for the current versions of  vue-chart.js. 
(Currently works with chart.js@4.2.1, chartjs-chart-geo@4.1.1, vue-chartjs@5.2.0)

`MapChart.vue`
```
<template>
    <Choropleth :data="chartData" />
  </template>

<script>
import { createTypedChart } from "vue-chartjs";
import { Chart, Tooltip } from 'chart.js';
import { ChoroplethController, GeoFeature, ColorScale, ProjectionScale } from 'chartjs-chart-geo';

Chart.register(ChoroplethController, GeoFeature, ColorScale, ProjectionScale, Tooltip);

const Choropleth = createTypedChart("choropleth", "choropleth");

export default {
  name: 'MapChart',
  components: { Choropleth },
  props: {
        chartData: {
            type: Object,
            default: ()=> {},
        },
    },
  
}

</script>
```
This assumes that the label and dataset keys will be passed through to the component.

**Comment by DaniilRyb** [comment]
> Hey Team! Just in case @nikolaBrkusanin still needs another way to use `chartjs-chart-geo` with `vue`. I share you the way I integrated both, `vue-charts-3` and `chartjs-chart-geo`.
> 
> `MyChoroplethChart.ts`
> 
> ```
> import { defineChartComponent } from 'vue-chart-3'
> import { Chart } from 'chart.js'
> import { ChoroplethController, GeoFeature, ColorScale, ProjectionScale } from 'chartjs-chart-geo'
> 
> Chart.register(ChoroplethController, GeoFeature, ColorScale, ProjectionScale)
> 
> export const MyChoroplethChart = defineChartComponent('choropleth-chart', 'choropleth')
> ```
> 
> `MyPage.vue`
> 
> ```
> <script setup lang="ts">
>   import { MyChoroplethChart } from './MyChoroplethChart'
>   const data = {...}
>   const options = {...}
> </script>
> <template>
>   <MyChoroplethChart :chartData="data" :options="options" />
> </template>
> ```

Thank you! This rows:
```
import { ChoroplethController, GeoFeature, ColorScale, ProjectionScale } from 'chartjs-chart-geo'
Chart.register(ChoroplethController, GeoFeature, ColorScale, ProjectionScale)
```

helped with also React. My error was: "choropleth" is not a registered controller.
    at Registry._get (webpack-internal:///./node_modules/chart.js/dist/chart.mjs:4059:13)
    at Registry.getController (webpack-internal:///./node_modules/chart.js/dist/chart.mjs:4005:17)
    at Chart.buildOrUpdateControllers (webpack-internal:///./node_modules/chart.js/dist/chart.mjs:5710:42)
    at Chart.update (webpack-internal:///./node_modules/chart.js/dist/chart.mjs:5744:33)
    at new Chart (webpack-internal:///./node_modules/chart.js/dist/chart.mjs:5526:12)
    at eval (webpack-internal:///./src/components/charts/map/Map.tsx:30:27)
