### ISSUE TITLE
The color scale is cutoff 

### ISSUE THREAD

**Issue by bnisevic** [sgratzl/chartjs-chart-geo#66]
** Issue **
I see this issue in FF and Chrome. The color scale is cutoff on one side. When options.scales.color.legend.align = 'right' or 'left' it is cutoff from two sides, but one side can be fixed with options.scales.color.legend.width. But there is no height property which can be used. https://github.com/sgratzl/chartjs-chart-geo/blob/main/src/scales/LegendScale.ts#L23-L70

Here it is how this can be fixed with width property. From this:

![Screenshot_2021-04-22 Diffbot - Search](https://user-images.githubusercontent.com/1433428/115865226-540a0a00-a438-11eb-96a7-c3f9d608b457.png)

to this

![Screenshot from 2021-04-23 13-19-21](https://user-images.githubusercontent.com/1433428/115865250-5f5d3580-a438-11eb-993d-19af0b8bc1d8.png)

So, the highest digit is still cutoff from the top, other digits are displayed correctly with increased options.scales.color.legend.width. But this also happens in other color scale alignments. Here is how it looks like for the "top" alignment:

![Screenshot_2021-04-23 Diffbot - Searc1221h](https://user-images.githubusercontent.com/1433428/115865441-992e3c00-a438-11eb-9124-6a5fd939d781.png)

The zero is cut off and this can not be fixed with options.scales.color.legend.width.

**Expected behavior**

Color scale should be complete, no digits should be cutoff.

**Comment by sgratzl** [comment]
should be fixed in https://github.com/sgratzl/chartjs-chart-geo/releases/tag/v3.0.2
