### ISSUE TITLE
Change Color of Legend Scale 

### ISSUE THREAD

**Issue by JasneetDua** [sgratzl/chartjs-chart-geo#68]
Is it possible to customize the legend scale color palette apart from using standard interpolations?
On passing color palette in datasets.backgroundColor as an array the map areas react accordingly but the scale doesn't;

Attaching code link for same:
https://codepen.io/JasneetDua/pen/yLgrZxZ?editors=0110

**Screenshots / Sketches**
![image](https://user-images.githubusercontent.com/28077207/116551220-53c8ad80-a915-11eb-87c9-e4025db876c8.png)

**Context**
- Version: 3.2.0
- Browser: Chrome

**Comment by sgratzl** [comment]
you can customize the interpolate function like in 

https://github.com/sgratzl/chartjs-chart-geo/blob/009397f09587eb8269ac0f7f3dab211e8d0588db/samples/albersCustom.html#L45

The input will be a numeric value, not the region since the scale doesn't know anything about regions but just the scale

**Comment by JasneetDua** [comment]
Thanks for your prompt answer.
I'm still wondering that can't we use an instance of  `CanvasRenderingContext2D.createLinearGradient()` to determine the color scale?

**Comment by sgratzl** [comment]
this plugin is designed to generate the colors both for coloring the regions and for rendering the color legend. A choropleth map is a visualization technique to encode a numeric value per geographic region in its color. The legend of a choropleth map illustrates which color corresponds to which numeric value.
