### ISSUE TITLE
Custom Topojson map not rendering.

### ISSUE THREAD

**Issue by Akashpatel1122** [sgratzl/chartjs-chart-geo#69]
I am trying to render custom topojson map with this library, however I am not able to render the map.
Following is my codepen. 
https://codepen.io/akashpatel1122/pen/XWpLGJQ
I will really appreciate if you could take a look at the issue.

**Comment by Akashpatel1122** [comment]
It is solved. It seems problem was with topojson file, When I used Geojson file instead everything worked perfectly.

**Comment by sgratzl** [comment]
glad to hear, btw I could also manage to fix your codepen: https://codepen.io/sgratzl/pen/poRMEqb?editors=0010. The issue was a mix up between the old chart.js config version and the new one
