### ISSUE TITLE
Europe map

### ISSUE THREAD

**Issue by jhoelzl** [sgratzl/chartjs-chart-geo#7]
Hello, can you please tell me how to visualize a map of all European countries? Thank you!

**Comment by sgratzl** [comment]
does https://github.com/leakyMirror/map-of-europe/blob/master/TopoJSON/europe.topojson this one work for you?
or https://github.com/deldersveld/topojson/blob/master/continents/europe.json

just google for `topojson europe` and you should find some files

**Comment by jhoelzl** [comment]
Thank you, i used your `choropleth ` example for US (https://codepen.io/sgratzl/pen/GRKLQBw) and adjusted the JS code now:

```
fetch('https://raw.githubusercontent.com/deldersveld/topojson/master/continents/europe.json').then((r) => r.json()).then((data) => {
      const countries = ChartGeo.topojson.feature(data, data.objects.continent_Europe_subunits).features;
      const chart = new Chart(document.getElementById("canvas").getContext("2d"), {
        type: 'choropleth',
        data: {
          labels: countries.map((d) => d.properties.name),
          datasets: [{
            label: 'Countries',
            backgroundColor: (context) => {
              if (context.dataIndex == null) {
                return null;
              }
              const value = context.dataset.data[context.dataIndex];
              return new Color('steelblue').lightness(value.value * 100).rgbString();
            },
            data: countries.map((d) => ({feature: d, value: Math.random()})),
          }]
        },
        options: {
          showOutline: true,
          showGraticule: true,
          legend: {
            display: false
          },
          scale: {
            projection: 'mercator'
          },
          onClick: (evt, elems) => {
            console.log(elems.map((elem) => elem.feature.properties.name));
          }
        }
      });
    });
```

The europe map appears and their countries, but it is very small in the middle of the canvas container. What can i do to fit the map to all the space of the canvas container?

**Comment by sgratzl** [comment]
I played around a bit at https://codepen.io/sgratzl/pen/mdyENoX. In the end you have to specify: `outline: countries` which act like the bounding box area such that the chart will automatically focus on this one. Tho, I'm not sure why it is not fully centered

**Comment by jhoelzl** [comment]
Thank you, i really appreciate your support!

**Comment by tejasvinik02** [comment]
https://raw.githubusercontent.com/deldersveld/topojson/master/continents/europe.json
Above url is not working. Can you please look into it?

**Comment by m-sidewinder** [comment]
Does not work
