### ISSUE TITLE
ChartJS V3 animations issue

### ISSUE THREAD

**Issue by kartblanch** [sgratzl/chartjs-chart-geo#71]
Hi!
After update a chart (`type: 'choropleth'`) I have an error `Cannot add property $animations, object is not extensible`.
So I have a question about how I can delete choropleth animation in ChartJS V3?

**Comment by sgratzl** [comment]
can you create an example on Codepen,... which reproduces it?

**Comment by sgratzl** [comment]
stale -> closing
