### ISSUE TITLE
README: some links lead to a 404

### ISSUE THREAD

**Issue by xlemmingx** [sgratzl/chartjs-chart-geo#80]
Some links in README.md are broken and lead to outdated (?) files. Example under headline **Options**:

`
see https://github.com/sgratzl/chartjs-chart-geo/blob/develop/src/controllers/geo.ts#L213
`

**To Reproduce**

1. Click link

**Expected behavior**

Page with more details loads.

**Comment by sgratzl** [comment]
has been already fixed in the dev branch via #74
