### ISSUE TITLE
Problems with the rendering of the map with the Italian provinces

### ISSUE THREAD

**Issue by vincepich** [sgratzl/chartjs-chart-geo#82]
I'm having the following question...
I am using Chart.js with Chart.js Geo without problems with files like https://unpkg.com/world-atlas/countries-50m.json and settings like this: scales: {
xy: {
projection: 'equalEarth'
}
}
However I am unable to view files such as:
https://raw.githubusercontent.com/deldersveld/topojson/master/countries/italy/italy-provinces.json
or https://github.com/openpolis/geojson-italy/blob/master/topojson/limits_IT_provinces.topo.json

Is there anything I need to put in the **projection** property?
What can I do?

**Comment by stockiNail** [comment]
@vincepich I am using Italy provinces and I am using:

https://raw.githubusercontent.com/deldersveld/topojson/master/countries/italy/italy-provinces.json

This is the result:

![geoIt](https://user-images.githubusercontent.com/11741250/126501520-a6989f83-7e92-4375-906a-61d7a9db3a49.png)

See codepen: https://codepen.io/stockinail/pen/WNpqEyd

**Comment by vincepich** [comment]
> See codepen: https://codepen.io/stockinail/pen/WNpqEyd
Thank you very much @stockiNail!!!
