### ISSUE TITLE
BubbleMap doesn't work with CHART.js 3.5.0

### ISSUE THREAD

**Issue by stockiNail** [sgratzl/chartjs-chart-geo#83]
I have used the sample bubbleMapArea.html and recreated in Codepen, using new CHART.JS 3.5.0:

https://codepen.io/stockinail/pen/XWRVxGb

As you can see, the bubbles are not shown. If you change CHART.JS version, using 3.4.1, it works.

**To Reproduce**

See in codepen: https://codepen.io/stockinail/pen/XWRVxGb

**Context**

- Version: geo 3.1.0, chart.js 3.5.0
- Browser: FF 90.0.2

**Comment by pate313373** [comment]
Same problem for geo 2.1.0 and chart.js 2.9.3

**Comment by stockiNail** [comment]
The issue is related to new element draw logic in CHART.JS 3.5.0:

https://github.com/chartjs/Chart.js/blob/566d7224312150268386aeec698da94e4a0cc566/src/elements/element.point.js#L53-L65
```javascript
  draw(ctx, area) {
    const me = this;
    const options = me.options;


    if (me.skip || options.radius < 0.1 || !_isPointInArea(me, area, me.size(options) / 2)) {
      return;
    }


    ctx.strokeStyle = options.borderColor;
    ctx.lineWidth = options.borderWidth;
    ctx.fillStyle = options.backgroundColor;
    drawPoint(ctx, options, me.x, me.y);
  }
```

In this new version, new check has been added:  `!_isPointInArea(me, area, me.size(options) / 2))`

which is using the `area` passed as argument. Unfortunately, the geo controller is not passing any `chartArea` to `draw` method of element:

https://github.com/sgratzl/chartjs-chart-geo/blob/71aee67748d35f6bc9b3247574e9b0e9e6cb80a9/src/controllers/GeoController.ts#L212

**Comment by stockiNail** [comment]
As you can see, open an issue to CHART.JS because the signature of `draw` method of elements type is not correct.
`chartArea` is missing but mandatory.

**Comment by sgratzl** [comment]
I implemented a workaround in the latest version of this plugin
