### ISSUE TITLE
Problem with Dataset

### ISSUE THREAD

**Issue by jhoelzl** [sgratzl/chartjs-chart-geo#9]
Hello, i am using the Europe map and your example to have a dataset with random values for all countries which works fine: https://codepen.io/sgratzl/pen/mdyENoX

However, when i want to define values on my own, the map gets empty. I just replace the line 

```
 data: countries.map((d) => ({feature: d, value: Math.random()})),
```
by
```
data: [
        { value: 0.4, feature: Germany },
        { value: 0.3, feature: Austria }
      ]
```
as written in section "Data Structure" in the README.md (https://github.com/sgratzl/chartjs-chart-geo).

**Comment by sgratzl** [comment]
I'm playing with https://codepen.io/sgratzl/pen/qBEqNpJ and got no problem so far, can you elaborate how you came to `Germany` and `Austria`?

**Comment by jhoelzl** [comment]
Germany and Austria are countries within Europe (https://raw.githubusercontent.com/deldersveld/topojson/master/continents/europe.json).

**Comment by sgratzl** [comment]
I adopted https://codepen.io/sgratzl/pen/mdyENoX?editors=0010 and it works as expected

**Comment by jhoelzl** [comment]
Thank you!
