### ISSUE TITLE
Choropleth chart capabilities

### ISSUE THREAD

**Issue by it-limon** [sgratzl/chartjs-chart-geo#90]
Good afternoon!
Could you provide advice on the capabilities of your choropleth chart for displaying maps.
1. Is it possible to customize the format of the popup hint text?
For example:
- is it possible to change the order of the information in it - first the value, and then the name of the region;
- is it possible to print part of the text in bold.
2. Is it possible to specify the boundaries of the intervals on the basis of which the map is colored? Or is the formation of interval boundaries embedded in the algorithm and is not subject to configuration by an application programmer?
3. Is it possible to display the capitals of the regions in the form of small round markers? We attach an example of a map for understanding.
4. Is it possible to export the map to png and pdf formats?
We are grateful in advance for the answers.
![Example](https://user-images.githubusercontent.com/72297475/138225390-73a45360-6a53-4dc2-8219-1f79e3dfde4b.png)

**Comment by sgratzl** [comment]
>     1. Is it possible to specify the boundaries of the intervals on the basis of which the map is colored? Or is the formation of interval boundaries embedded in the algorithm and is not subject to configuration by an application programmer?

see also https://github.com/sgratzl/chartjs-chart-geo/blob/0c817cea57ad5aba6cde834e58e1a489fbf092f5/src/scales/ColorScale.ts#L120-L171

you can customize the coloring function by setting the `interpolate` option to a custom function that converts a normalized value to a color. 

an alternative with even more flexibility is setting the `backgroundColor` on the `geoFeature` see also https://github.com/sgratzl/chartjs-chart-geo/blob/0c817cea57ad5aba6cde834e58e1a489fbf092f5/src/controllers/ChoroplethController.ts#L125-L127

**Comment by stockiNail** [comment]
@sgratzl correct me if I'm wrong but you cannot change the color of the boundaries, by a scriptable options.

having a look to the image, published here by @it-limon, the boundaries of the states have a different color, maybe based on some logic.
