### ISSUE TITLE
How to apply logarithmic scale on color values

### ISSUE THREAD

**Issue by pierredarrieutort** [sgratzl/chartjs-chart-geo#91]
As I've seen at #68 we can change the scale of colors in legend.
So I've applied that but the results are not changing on the choropleth itself. The only change is on legend scale.
I've made a simple Codepen to demonstrate my issue : **https://codepen.io/Pierre-Darrieutort/pen/YzxEaoj**

The first choropleth _(img1)_ use a linear scale and the second _(img2)_ a log scale but the map renderer is the same.
(And btw the interpolation between two colors is terrible but I don't know how to do in other way like at https://github.com/sgratzl/chartjs-chart-geo/issues/57#issuecomment-808315719

So the question is "how can I apply log scale on my choropleth colors ?"

**Screenshots / Sketches**

![image](https://user-images.githubusercontent.com/25182438/139852237-6939dfa2-2050-4e38-b321-f21ce21c0c3a.png)
![image](https://user-images.githubusercontent.com/25182438/139852281-56d32575-46b9-44ac-84f7-d96f133cc6a1.png)

**Comment by sgratzl** [comment]
looking at your values, all values except US are very small. So they will appear as gray in both setups. https://github.com/sgratzl/chartjs-chart-geo/blob/main/samples/albersLog.html is a basic example of using the log scale. I think you are using it correctly but your data and color transformation let it look the same.
