### ISSUE TITLE
Labels on bubbleMap

### ISSUE THREAD

**Issue by jansipke** [sgratzl/chartjs-chart-geo#93]
In the screenshot on the homepage of this project there are labels visible just above the bubbles in the bubbleMap:
https://user-images.githubusercontent.com/4129778/78821935-89cd8380-79da-11ea-81bf-842fcbd3eff4.png

However, in the linked codepen at https://codepen.io/sgratzl/pen/YzyJRvm the labels are not visible. Is there a way to show these labels?

**Comment by stockiNail** [comment]
@jansipke Datalabels plugin MUST be registered.
Since new versions, it doesn't register itself (as in the past).

Add `Chart.register(ChartDataLabels);` on the top of the sample.

More details here: https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#registration

**Comment by jansipke** [comment]
That works like a charm. Thanks @stockiNail

**Comment by bjangid20** [comment]
is there any way to show atleast two chars on countires while using choropleth.

seems like I am not able to show lables.

using version of chart js 3.9.1, chartjs geo version is 3.9.0

**Comment by sgratzl** [comment]
sees the link to the chart.js data labels plugin
